//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for APIIndexVersion.
const (
	V1 APIIndexVersion = "v1"
)

// Valid indicates whether the value is a known member of the APIIndexVersion enum.
func (e APIIndexVersion) Valid() bool {
	switch e {
	case V1:
		return true
	default:
		return false
	}
}

// Defines values for AnalyticsEventLocale.
const (
	En AnalyticsEventLocale = "en"
	Ru AnalyticsEventLocale = "ru"
)

// Valid indicates whether the value is a known member of the AnalyticsEventLocale enum.
func (e AnalyticsEventLocale) Valid() bool {
	switch e {
	case En:
		return true
	case Ru:
		return true
	default:
		return false
	}
}

// Defines values for GameEntityLocale.
const (
	GameEntityLocaleEnUS GameEntityLocale = "en_US"
	GameEntityLocaleRuRU GameEntityLocale = "ru_RU"
)

// Valid indicates whether the value is a known member of the GameEntityLocale enum.
func (e GameEntityLocale) Valid() bool {
	switch e {
	case GameEntityLocaleEnUS:
		return true
	case GameEntityLocaleRuRU:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ListGameEntitiesParamsLocale.
const (
	ListGameEntitiesParamsLocaleEnUS ListGameEntitiesParamsLocale = "en_US"
	ListGameEntitiesParamsLocaleRuRU ListGameEntitiesParamsLocale = "ru_RU"
)

// Valid indicates whether the value is a known member of the ListGameEntitiesParamsLocale enum.
func (e ListGameEntitiesParamsLocale) Valid() bool {
	switch e {
	case ListGameEntitiesParamsLocaleEnUS:
		return true
	case ListGameEntitiesParamsLocaleRuRU:
		return true
	default:
		return false
	}
}

// Defines values for GetGameEntityParamsLocale.
const (
	GetGameEntityParamsLocaleEnUS GetGameEntityParamsLocale = "en_US"
	GetGameEntityParamsLocaleRuRU GetGameEntityParamsLocale = "ru_RU"
)

// Valid indicates whether the value is a known member of the GetGameEntityParamsLocale enum.
func (e GetGameEntityParamsLocale) Valid() bool {
	switch e {
	case GetGameEntityParamsLocaleEnUS:
		return true
	case GetGameEntityParamsLocaleRuRU:
		return true
	default:
		return false
	}
}

// APIError defines model for APIError.
type APIError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// APIIndex defines model for APIIndex.
type APIIndex struct {
	Graphql string          `json:"graphql"`
	Rest    string          `json:"rest"`
	Version APIIndexVersion `json:"version"`
}

// APIIndexVersion defines model for APIIndex.Version.
type APIIndexVersion string

// AnalyticsEvent defines model for AnalyticsEvent.
type AnalyticsEvent struct {
	EventId    *openapi_types.UUID     `json:"eventId,omitempty"`
	EventName  string                  `json:"eventName"`
	Locale     AnalyticsEventLocale    `json:"locale"`
	OccurredAt *time.Time              `json:"occurredAt,omitempty"`
	Path       string                  `json:"path"`
	Properties *map[string]interface{} `json:"properties,omitempty"`
	SessionId  openapi_types.UUID      `json:"sessionId"`
	UserId     *openapi_types.UUID     `json:"userId,omitempty"`
	Value      *float64                `json:"value,omitempty"`
}

// AnalyticsEventLocale defines model for AnalyticsEvent.Locale.
type AnalyticsEventLocale string

// AnalyticsOverview defines model for AnalyticsOverview.
type AnalyticsOverview struct {
	ActiveSubscriptions int64            `json:"activeSubscriptions"`
	Events              int64            `json:"events"`
	Hours               int              `json:"hours"`
	Series              []AnalyticsPoint `json:"series"`
	UniqueUsers         int64            `json:"uniqueUsers"`
}

// AnalyticsPoint defines model for AnalyticsPoint.
type AnalyticsPoint struct {
	Events      int64     `json:"events"`
	Hour        time.Time `json:"hour"`
	UniqueUsers int64     `json:"uniqueUsers"`
}

// CursorPage defines model for CursorPage.
type CursorPage struct {
	HasMore    bool    `json:"hasMore"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

// GameEntity defines model for GameEntity.
type GameEntity struct {
	BuildId     *int64                 `json:"buildId,omitempty"`
	Description string                 `json:"description"`
	ExternalId  int64                  `json:"externalId"`
	Id          openapi_types.UUID     `json:"id"`
	Locale      GameEntityLocale       `json:"locale"`
	Name        string                 `json:"name"`
	Payload     map[string]interface{} `json:"payload"`
	Product     string                 `json:"product"`
	Slug        string                 `json:"slug"`
	Type        string                 `json:"type"`
	UpdatedAt   time.Time              `json:"updatedAt"`
}

// GameEntityLocale defines model for GameEntity.Locale.
type GameEntityLocale string

// GameEntityPage defines model for GameEntityPage.
type GameEntityPage struct {
	Data       []GameEntity `json:"data"`
	Pagination CursorPage   `json:"pagination"`
}

// GameProduct defines model for GameProduct.
type GameProduct struct {
	Id   int32  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// IndexNowRequest defines model for IndexNowRequest.
type IndexNowRequest struct {
	Urls []string `json:"urls"`
}

// IngestEventsRequest defines model for IngestEventsRequest.
type IngestEventsRequest struct {
	Events []AnalyticsEvent `json:"events"`
}

// IngestEventsResponse defines model for IngestEventsResponse.
type IngestEventsResponse struct {
	Accepted int `json:"accepted"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// QueuedResponse defines model for QueuedResponse.
type QueuedResponse struct {
	Queued bool `json:"queued"`
}

// BadRequest defines model for BadRequest.
type BadRequest = APIError

// InternalError defines model for InternalError.
type InternalError = APIError

// NotFound defines model for NotFound.
type NotFound = Problem

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Problem

// GetAnalyticsOverviewParams defines parameters for GetAnalyticsOverview.
type GetAnalyticsOverviewParams struct {
	Hours *int `form:"hours,omitempty" json:"hours,omitempty"`
}

// ListGameEntitiesParams defines parameters for ListGameEntities.
type ListGameEntitiesParams struct {
	Product *string                       `form:"product,omitempty" json:"product,omitempty"`
	Type    *string                       `form:"type,omitempty" json:"type,omitempty"`
	Locale  *ListGameEntitiesParamsLocale `form:"locale,omitempty" json:"locale,omitempty"`
	Q       *string                       `form:"q,omitempty" json:"q,omitempty"`

	// Cursor Opaque cursor from the previous response.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListGameEntitiesParamsLocale defines parameters for ListGameEntities.
type ListGameEntitiesParamsLocale string

// GetGameEntityParams defines parameters for GetGameEntity.
type GetGameEntityParams struct {
	Locale *GetGameEntityParamsLocale `form:"locale,omitempty" json:"locale,omitempty"`
}

// GetGameEntityParamsLocale defines parameters for GetGameEntity.
type GetGameEntityParamsLocale string

// IngestAnalyticsEventsJSONRequestBody defines body for IngestAnalyticsEvents for application/json ContentType.
type IngestAnalyticsEventsJSONRequestBody = IngestEventsRequest

// SubmitIndexNowJSONRequestBody defines body for SubmitIndexNow for application/json ContentType.
type SubmitIndexNowJSONRequestBody = IndexNowRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetLiveness Check whether the API process is alive.
	// (GET /livez)
	GetLiveness(w http.ResponseWriter, r *http.Request)
	// GetReadiness Check whether required datastores are ready.
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
	// GetAPIIndex Discover the stable v1 API surfaces.
	// (GET /v1)
	GetAPIIndex(w http.ResponseWriter, r *http.Request)
	// IngestAnalyticsEvents Ingest a batch of product analytics events.
	// (POST /v1/analytics/events)
	IngestAnalyticsEvents(w http.ResponseWriter, r *http.Request)
	// GetAnalyticsOverview Read an aggregated analytics overview.
	// (GET /v1/analytics/overview)
	GetAnalyticsOverview(w http.ResponseWriter, r *http.Request, params GetAnalyticsOverviewParams)
	// ListGameEntities Search and page through versioned game entities.
	// (GET /v1/game/entities)
	ListGameEntities(w http.ResponseWriter, r *http.Request, params ListGameEntitiesParams)
	// GetGameEntity Get the latest version of a game entity.
	// (GET /v1/game/entities/{id})
	GetGameEntity(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetGameEntityParams)
	// ListGameProducts List supported World of Warcraft products.
	// (GET /v1/game/products)
	ListGameProducts(w http.ResponseWriter, r *http.Request)
	// SubmitIndexNow Queue URLs for IndexNow submission.
	// (POST /v1/indexnow)
	SubmitIndexNow(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAPIIndex operation middleware
func (siw *ServerInterfaceWrapper) GetAPIIndex(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAPIIndex(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IngestAnalyticsEvents operation middleware
func (siw *ServerInterfaceWrapper) IngestAnalyticsEvents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IngestAnalyticsEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAnalyticsOverview operation middleware
func (siw *ServerInterfaceWrapper) GetAnalyticsOverview(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAnalyticsOverviewParams

	// ------------- Optional query parameter "hours" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "hours", r.URL.Query(), &params.Hours, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "hours"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hours", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAnalyticsOverview(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGameEntities operation middleware
func (siw *ServerInterfaceWrapper) ListGameEntities(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGameEntitiesParams

	// ------------- Optional query parameter "product" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "product", r.URL.Query(), &params.Product, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "product"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "product", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "locale" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "locale", r.URL.Query(), &params.Locale, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "locale"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locale", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGameEntities(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGameEntity operation middleware
func (siw *ServerInterfaceWrapper) GetGameEntity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGameEntityParams

	// ------------- Optional query parameter "locale" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "locale", r.URL.Query(), &params.Locale, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "locale"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locale", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGameEntity(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGameProducts operation middleware
func (siw *ServerInterfaceWrapper) ListGameProducts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGameProducts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitIndexNow operation middleware
func (siw *ServerInterfaceWrapper) SubmitIndexNow(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitIndexNow(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1", wrapper.GetAPIIndex)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/game/products", wrapper.ListGameProducts)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/game/entities", wrapper.ListGameEntities)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/game/entities/{id}", wrapper.GetGameEntity)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/livez", wrapper.GetLiveness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.GetReadiness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/analytics/overview", wrapper.GetAnalyticsOverview)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/analytics/events", wrapper.IngestAnalyticsEvents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/indexnow", wrapper.SubmitIndexNow)

	return m
}

type BadRequestJSONResponse APIError

type InternalErrorJSONResponse APIError

type NotFoundApplicationProblemPlusJSONResponse Problem

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers TooManyRequestsResponseHeaders
}

type GetLivenessRequestObject struct {
}

type GetLivenessResponseObject interface {
	VisitGetLivenessResponse(w http.ResponseWriter) error
}

type GetLiveness200JSONResponse HealthResponse

func (response GetLiveness200JSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetLiveness429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetLiveness429ApplicationProblemPlusJSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse HealthResponse

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadiness429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetReadiness429ApplicationProblemPlusJSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadiness503JSONResponse APIError

func (response GetReadiness503JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetAPIIndexRequestObject struct {
}

type GetAPIIndexResponseObject interface {
	VisitGetAPIIndexResponse(w http.ResponseWriter) error
}

type GetAPIIndex200JSONResponse APIIndex

func (response GetAPIIndex200JSONResponse) VisitGetAPIIndexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAPIIndex429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetAPIIndex429ApplicationProblemPlusJSONResponse) VisitGetAPIIndexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type IngestAnalyticsEventsRequestObject struct {
	Body *IngestAnalyticsEventsJSONRequestBody
}

type IngestAnalyticsEventsResponseObject interface {
	VisitIngestAnalyticsEventsResponse(w http.ResponseWriter) error
}

type IngestAnalyticsEvents202JSONResponse IngestEventsResponse

func (response IngestAnalyticsEvents202JSONResponse) VisitIngestAnalyticsEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type IngestAnalyticsEvents400JSONResponse struct{ BadRequestJSONResponse }

func (response IngestAnalyticsEvents400JSONResponse) VisitIngestAnalyticsEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type IngestAnalyticsEvents500JSONResponse struct{ InternalErrorJSONResponse }

func (response IngestAnalyticsEvents500JSONResponse) VisitIngestAnalyticsEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAnalyticsOverviewRequestObject struct {
	Params GetAnalyticsOverviewParams
}

type GetAnalyticsOverviewResponseObject interface {
	VisitGetAnalyticsOverviewResponse(w http.ResponseWriter) error
}

type GetAnalyticsOverview200JSONResponse AnalyticsOverview

func (response GetAnalyticsOverview200JSONResponse) VisitGetAnalyticsOverviewResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAnalyticsOverview429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetAnalyticsOverview429ApplicationProblemPlusJSONResponse) VisitGetAnalyticsOverviewResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetAnalyticsOverview500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetAnalyticsOverview500JSONResponse) VisitGetAnalyticsOverviewResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListGameEntitiesRequestObject struct {
	Params ListGameEntitiesParams
}

type ListGameEntitiesResponseObject interface {
	VisitListGameEntitiesResponse(w http.ResponseWriter) error
}

type ListGameEntities200JSONResponse GameEntityPage

func (response ListGameEntities200JSONResponse) VisitListGameEntitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListGameEntities400JSONResponse struct{ BadRequestJSONResponse }

func (response ListGameEntities400JSONResponse) VisitListGameEntitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListGameEntities500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListGameEntities500JSONResponse) VisitListGameEntitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetGameEntityRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params GetGameEntityParams
}

type GetGameEntityResponseObject interface {
	VisitGetGameEntityResponse(w http.ResponseWriter) error
}

type GetGameEntity200JSONResponse GameEntity

func (response GetGameEntity200JSONResponse) VisitGetGameEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetGameEntity404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetGameEntity404ApplicationProblemPlusJSONResponse) VisitGetGameEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetGameEntity500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetGameEntity500JSONResponse) VisitGetGameEntityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListGameProductsRequestObject struct {
}

type ListGameProductsResponseObject interface {
	VisitListGameProductsResponse(w http.ResponseWriter) error
}

type ListGameProducts200JSONResponse struct {
	Data []GameProduct `json:"data"`
}

func (response ListGameProducts200JSONResponse) VisitListGameProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListGameProducts429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response ListGameProducts429ApplicationProblemPlusJSONResponse) VisitListGameProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListGameProducts500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListGameProducts500JSONResponse) VisitListGameProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitIndexNowRequestObject struct {
	Body *SubmitIndexNowJSONRequestBody
}

type SubmitIndexNowResponseObject interface {
	VisitSubmitIndexNowResponse(w http.ResponseWriter) error
}

type SubmitIndexNow202JSONResponse QueuedResponse

func (response SubmitIndexNow202JSONResponse) VisitSubmitIndexNowResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitIndexNow400JSONResponse struct{ BadRequestJSONResponse }

func (response SubmitIndexNow400JSONResponse) VisitSubmitIndexNowResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitIndexNow500JSONResponse struct{ InternalErrorJSONResponse }

func (response SubmitIndexNow500JSONResponse) VisitSubmitIndexNowResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetLiveness Check whether the API process is alive.
	// (GET /livez)
	GetLiveness(ctx context.Context, request GetLivenessRequestObject) (GetLivenessResponseObject, error)
	// GetReadiness Check whether required datastores are ready.
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
	// GetAPIIndex Discover the stable v1 API surfaces.
	// (GET /v1)
	GetAPIIndex(ctx context.Context, request GetAPIIndexRequestObject) (GetAPIIndexResponseObject, error)
	// IngestAnalyticsEvents Ingest a batch of product analytics events.
	// (POST /v1/analytics/events)
	IngestAnalyticsEvents(ctx context.Context, request IngestAnalyticsEventsRequestObject) (IngestAnalyticsEventsResponseObject, error)
	// GetAnalyticsOverview Read an aggregated analytics overview.
	// (GET /v1/analytics/overview)
	GetAnalyticsOverview(ctx context.Context, request GetAnalyticsOverviewRequestObject) (GetAnalyticsOverviewResponseObject, error)
	// ListGameEntities Search and page through versioned game entities.
	// (GET /v1/game/entities)
	ListGameEntities(ctx context.Context, request ListGameEntitiesRequestObject) (ListGameEntitiesResponseObject, error)
	// GetGameEntity Get the latest version of a game entity.
	// (GET /v1/game/entities/{id})
	GetGameEntity(ctx context.Context, request GetGameEntityRequestObject) (GetGameEntityResponseObject, error)
	// ListGameProducts List supported World of Warcraft products.
	// (GET /v1/game/products)
	ListGameProducts(ctx context.Context, request ListGameProductsRequestObject) (ListGameProductsResponseObject, error)
	// SubmitIndexNow Queue URLs for IndexNow submission.
	// (POST /v1/indexnow)
	SubmitIndexNow(ctx context.Context, request SubmitIndexNowRequestObject) (SubmitIndexNowResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetLiveness operation middleware
func (sh *strictHandler) GetLiveness(w http.ResponseWriter, r *http.Request) {
	var request GetLivenessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLiveness(ctx, request.(GetLivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLiveness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLivenessResponseObject); ok {
		if err := validResponse.VisitGetLivenessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAPIIndex operation middleware
func (sh *strictHandler) GetAPIIndex(w http.ResponseWriter, r *http.Request) {
	var request GetAPIIndexRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAPIIndex(ctx, request.(GetAPIIndexRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAPIIndex")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAPIIndexResponseObject); ok {
		if err := validResponse.VisitGetAPIIndexResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// IngestAnalyticsEvents operation middleware
func (sh *strictHandler) IngestAnalyticsEvents(w http.ResponseWriter, r *http.Request) {
	var request IngestAnalyticsEventsRequestObject

	var body IngestAnalyticsEventsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.IngestAnalyticsEvents(ctx, request.(IngestAnalyticsEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IngestAnalyticsEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(IngestAnalyticsEventsResponseObject); ok {
		if err := validResponse.VisitIngestAnalyticsEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAnalyticsOverview operation middleware
func (sh *strictHandler) GetAnalyticsOverview(w http.ResponseWriter, r *http.Request, params GetAnalyticsOverviewParams) {
	var request GetAnalyticsOverviewRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAnalyticsOverview(ctx, request.(GetAnalyticsOverviewRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAnalyticsOverview")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAnalyticsOverviewResponseObject); ok {
		if err := validResponse.VisitGetAnalyticsOverviewResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListGameEntities operation middleware
func (sh *strictHandler) ListGameEntities(w http.ResponseWriter, r *http.Request, params ListGameEntitiesParams) {
	var request ListGameEntitiesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListGameEntities(ctx, request.(ListGameEntitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGameEntities")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListGameEntitiesResponseObject); ok {
		if err := validResponse.VisitListGameEntitiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGameEntity operation middleware
func (sh *strictHandler) GetGameEntity(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params GetGameEntityParams) {
	var request GetGameEntityRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGameEntity(ctx, request.(GetGameEntityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGameEntity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGameEntityResponseObject); ok {
		if err := validResponse.VisitGetGameEntityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListGameProducts operation middleware
func (sh *strictHandler) ListGameProducts(w http.ResponseWriter, r *http.Request) {
	var request ListGameProductsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListGameProducts(ctx, request.(ListGameProductsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGameProducts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListGameProductsResponseObject); ok {
		if err := validResponse.VisitListGameProductsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SubmitIndexNow operation middleware
func (sh *strictHandler) SubmitIndexNow(w http.ResponseWriter, r *http.Request) {
	var request SubmitIndexNowRequestObject

	var body SubmitIndexNowJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitIndexNow(ctx, request.(SubmitIndexNowRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitIndexNow")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitIndexNowResponseObject); ok {
		if err := validResponse.VisitSubmitIndexNowResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFpZcyO3Ef4rKCRv4fJa2XH4Jq83CqvkNSNlyw+uLVdz0CSxOwOMcHDFqPjfXTjmIsFDpeuNMwOgv/76",
	"QHdLDzSTRSkFCqPp5IEq1KUUGv3Dz8Bu8M6iNu4pk8Kg8D+hLHOegeFSDL5qKdw7na2wAPfr7woXdEL/",
	"NmiOHoSvenA5m35USiq63W57lKHOFC/dOXRCp2INOWdEBZl9uu3RqTCoBORh0+ugCBKJRrVGRdAt9Fg+",
	"SfNvaQU7AqNUcp5j8Y/HwZmFXSk0N6ilVRkSIQ1ZOOkeyv+k/BXEJlpHvyoiMEhyXnBD8D5DZMj6tEdX",
	"CAyVR3KDRm3eXS4Mqq5EsymRTigXBpfoyXfHR5luQW2XyQMtlSxRGY5RO4atI7RRXCwdEwVqDcvUt22P",
	"Ok/iChmd/BFOaNZ/6VXr5fwrZsaddTmbTgXD+33xSwXl6i53PxdSFWDohFrFaW8fkIrhcmrdGpXmwSaZ",
	"FG4PXY/2F+5oUe2Kcno1sqQ+AvKN4Zn+uI6e0dUK3esp66K1nKXg+rWfoPBMF3B/jWJpVnQyGg57tOCi",
	"fk7szWUGud+IwhZODfQa2BbqZrXMMqsUsssujQwMvjO8wBS6EpzsDrDx8OKn1MoOA8AYd34N+az13iiL",
	"CTo1asf9mYRZjerMpWvILXaVlXaetzQVtpj7iOl6Q2OUSEHNdRvtUdf4bY1qzfH7vndAZvgab+28jn7d",
	"wciF+fGigVhHdfSVcxevpA1pY/+TRhWxcIOFPpnVK51mkguvZTwSlIKNt4ngdxY/65ioTqLboTtArfXr",
	"ntdLElYrcdQIAXA6Ph/D4/kB8wxMHCIipekHq7RUs5iou1quQP8qVTuDz6XMEYTbKPDehM2nM3x1UArA",
	"FRT4URhuNvsA5pbnbCdUD/PcuQ0TFxLeh/rh7AP5eUkilUT//Hzr8+ifN5+TqVTEfJ3Il5tcAnt0CiyV",
	"ZDYzyTN1bpfJD+FF4oMtnY8+ItHvGNwTVUGKizsGiKBaWVGEZNk2YsNGG9FxJ0p7MgMDZ2erlkcmMlUJ",
	"Sy6gcrJj57RCa5cfj6dz1iGtZo1duyrxPS9+P0568UFXO+AWKVNGY/mjUkj/g5Cb1U1sUfbBagPG6naI",
	"yG+JuNgRHXelBPpq8JP83uqCuhKtyrv306mqr4D7aVg7Gg5j6VS92PWCHZxeVhrlErXxNZ4+iLS5Sx53",
	"l4bSsYP8h0cCj6JPQz9kV8gyLA2yZA/RlVUvTUmrupr9wEUDPE+6LxfagMjwHOM2/rcfH4abHI+mx+On",
	"7+gZc104tXfMh/9r0SI7TO6d/566fXdExoX7MraepoUMTLZ7xQ9SGAWZIXoFChmZb4hZIbmSZA7ZNxSM",
	"gGD+1Se8N/2vmiyUb2N9S5nzDCNkzlAYvuCuo6TX4f0NLt65K0txNKA2VeKY0PbLhnl6xXOmgFzOprTV",
	"fdFRf9gf+r6jRAElpxP6vj/qD2NJ7Tka5HyN//eNIPrYcgT6jOpueXqF5pqvUaDWoTFrRijj4fDZphY7",
	"6S/Rm8+UzFBrwjUBB9nPCi7G/zp0cg11sDtQ8I25LQrH4YR+WGH2jXxfoVmh8va6nE1JuS9t26MDhcA2",
	"R8m6QWD87dn6BUsUDEXGURNQSDzyJ3DWoz8M37/KkOqSVJFJWKXFxhnCClgDz2GeR3McMmKzHwxoI9UO",
	"B86S69ExK9bTkhc0Yi0jxcFsSlAYtSGla5+ey9d/4TqT6+jm2jgmyXrkHV5btYAMdU3PAKprctDcr6XU",
	"CcLCTde9VoP/exQ/S7Z5NtZSBcG2m85dfb/dM9z4hSAcjsGwglTXNllIRUBvREa40O6SkiIYNjjVccO2",
	"5tU+Fs/Y0p0vdz0h6ECAzMFkKyIXJPYapDY7CWZPOYRsDVYOhtDeFMZdOgoKNL4x/+OBcsfSncX2BVfN",
	"IRpTMFyAzQ2djC98pcYLV//+cxzqtPA0SnT1X14ydveUSwXxcqlw6XqufXKfmImfaH13SREQBBqEjdkr",
	"4zaGX0KBA1ek1CPjlM2vuTZ14+cWnmXvpsVtmG9NOn+86Exgx4naMX1uLCKf99BmALnvnfXI4twRxiEh",
	"d4dgj11rkjik63W/lXBnkWS+dXY1Z+GzfalwzaXVpPIQV4WmxIeNhzCMxj+dzxYvuDkQysNWKFdj9rcJ",
	"5Z3BRyKOwxTiXRw1ICMuHkgVD2+Wwm8RVLbyXUYJSyRmpaRdrkgs/xM4U+E8eOBseyyPt2Y56YCOw/lo",
	"dD/s6N7FbQ84MQp8ncB7HXdKudJVbZFYiw8vTjtB/bfZ5/CaKzQ+H+RgXAEQncUVANDyl82Ot8QsfTr5",
	"z6qFT6T4icPHaua3PTG+8Qenu/6u4W5tWUrVusrf+AZ3fBNdg/pdqpw5I/4OKlOwMG2Y0ZDcNRtCfj9c",
	"x9/aecFNNRh8sQK+O3d85eJ9Z2SU/CeJAJBoR4f/QyMJ86E3S/UeNPl8c619E5FA2A+ahP/rCMnZqtzV",
	"08aUejIYQMn7Sz8l6gt0qHYXNB/dWrr9sv0rAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
