/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discover the stable v1 API surfaces. */
        get: operations["getAPIIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/game/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List supported World of Warcraft products. */
        get: operations["listGameProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/library/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List curated public Warcraft datasets and their freshness and coverage. */
        get: operations["listLibraryDatasets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/game/entity-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List entity types and public catalog coverage metrics. */
        get: operations["listGameEntityTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/game/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search and page through versioned game entities. */
        get: operations["listGameEntities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/game/entity-summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search lightweight catalog cards without payloads or tooltips.
         * @description Use this endpoint for directories and search results. Fetch the full entity resource only when a user opens a detail view.
         */
        get: operations["listGameEntitySummaries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/game/sitemap-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a stable UUID shard for segmented catalog sitemaps.
         * @description Intended for Gildra's sitemap renderer. Empty shard means the complete entity type and is capped at 50000 records.
         */
        get: operations["listGameSitemapEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/game/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List populated catalog categories and their active entity counts. */
        get: operations["listGameCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/game/entities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the latest version of a game entity. */
        get: operations["getGameEntity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/game/entities/{id}/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Page through the normalized relationship graph for an entity. */
        get: operations["listGameEntityRelationships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/game/entities/{id}/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect completeness and provenance for the latest entity version. */
        get: operations["getGameEntityQuality"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/game/entities/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List build-pinned versions of an entity, newest first. */
        get: operations["listGameEntityVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/game/entities/{id}/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare two stored versions, or the two latest versions when builds are omitted. */
        get: operations["getGameEntityComparison"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/game/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect field coverage for the current catalog read model. */
        get: operations["listGameCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/game/source-policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reviewed source licensing and redistribution policy metadata. */
        get: operations["listGameSourcePolicies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/game/relation-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the canonical relationship ontology. */
        get: operations["listGameRelationTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check whether the API process is alive. */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check whether required datastores are ready. */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an aggregated analytics overview. */
        get: operations["getAnalyticsOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a batch of product analytics events. */
        post: operations["ingestAnalyticsEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/indexnow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue URLs for IndexNow submission. */
        post: operations["submitIndexNow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve a verified, locally cached catalog media object.
         * @description Media is exposed only when its source artifact, publication grant, cache integrity and retention window are valid. In private mode this endpoint requires the catalog session cookie.
         */
        get: operations["getCatalogMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graphql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute a read-only GraphQL catalog query.
         * @description GraphQL uses the same catalog session cookie and publication gate as REST. Query complexity and response size are bounded by the server.
         */
        post: operations["executeGraphQL"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIIndex: {
            /** @constant */
            version: "v1";
            /** Format: uri */
            rest: string;
            /** Format: uri */
            graphql: string;
            /** Format: uri */
            catalog: string;
            /** Format: uri */
            library: string;
            editions?: components["schemas"]["APIIndexEdition"][];
        };
        APIIndexEdition: {
            /** @enum {string} */
            edition: "retail" | "classic" | "classic-era" | "hardcore";
            product: string;
            /** Format: uri */
            base: string;
        };
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
        };
        GraphQLRequest: {
            query: string;
            operationName?: string;
            variables?: {
                [key: string]: unknown;
            };
        };
        GraphQLResponse: {
            data?: {
                [key: string]: unknown;
            };
            errors?: {
                [key: string]: unknown;
            }[];
        };
        GameProduct: {
            /** Format: int32 */
            id: number;
            slug: string;
            name: string;
            /**
             * Format: int32
             * @description Active client build number for this product, when a build has been imported.
             */
            buildNumber?: number;
            /** @description Active client version pinned to the product. */
            buildVersion?: string;
            /** @description Primary source used for the latest build freshness check. */
            source?: string;
            /**
             * Format: int32
             * @description Build number reported by the latest source check, when available.
             */
            sourceBuildNumber?: number;
            /** @description Build version reported by the latest source check, when available. */
            sourceBuildVersion?: string;
            /**
             * @description Raw status recorded by the latest source check.
             * @enum {string}
             */
            sourceStatus?: "current" | "update_available" | "failed";
            /**
             * Format: date-time
             * @description Time of the latest source check.
             */
            sourceCheckedAt?: string;
            /**
             * Format: int64
             * @description Number of non-deleted entities imported for the product.
             */
            entityCount: number;
            /**
             * Format: int64
             * @description Number of imported entities with a current published version pointer.
             */
            publishedEntityCount: number;
            /** @description True only when an atomic catalog release is currently selected for public reads. */
            publicRelease?: boolean;
            /**
             * @description Derived freshness of the imported active build versus the latest source check.
             * @enum {string}
             */
            freshness: "fresh" | "stale" | "failed" | "unknown";
            /** @description Human-readable explanation of the freshness state. */
            freshnessReason: string;
        };
        LibraryDataset: {
            slug: string;
            product: string;
            entityType: string;
            /** @description Taxonomy path used by the entity listing. Empty for an entire entity type. */
            categoryPath: string;
            /** @description Stable game item class filter used by item datasets such as Weapons and Armor. */
            itemClassId?: number;
            group: string;
            iconSymbol: string;
            sortOrder: number;
            name: string;
            description: string;
            buildVersion?: string;
            /**
             * Format: uri
             * @description Source-backed game icon selected for the dataset card when one is available.
             */
            previewImageUrl?: string;
            /** Format: int64 */
            entityCount: number;
            /**
             * Format: int64
             * @description Records with a localization row available for the requested locale.
             */
            localizedCount: number;
            /**
             * Format: int64
             * @description Localizations backed by a ready source artifact with content proof.
             */
            verifiedLocalizedCount: number;
            /** Format: int64 */
            tooltipCount: number;
            /** Format: int64 */
            imageCount: number;
            /**
             * @description Whether the dataset belongs to this game product, or is waiting for a permitted source.
             * @enum {string}
             */
            applicability: "applicable" | "pending_source" | "not_applicable";
            applicabilityReason: string;
            /** @enum {string} */
            freshness: "fresh" | "stale" | "empty" | "refreshing" | "failed";
            freshnessReason: string;
            /** Format: date-time */
            coverageUpdatedAt?: string;
        };
        GameEntityLocalization: {
            /** @description Source-backed name in the requested locale. Empty means the source has no value. */
            name: string;
            /** @description Source-backed description in the requested locale. Empty means the source has no value. */
            description: string;
            /** @description Display-ready description after resolving build-pinned DB2 value tokens. Empty means no source value. */
            resolvedDescription: string;
            /** @description present when resolved display text is available, missing when the source has no description, or unresolved when Blizzard template tokens remain. */
            descriptionState: string;
        };
        GameEntity: {
            /** Format: uuid */
            id: string;
            product: string;
            type: string;
            /** Format: int64 */
            externalId: number;
            slug: string;
            /** @enum {string} */
            locale: "en_US" | "ru_RU";
            /**
             * @description Locale that actually supplied the canonical displayed name.
             * @enum {string}
             */
            resolvedLocale: "en_US" | "ru_RU";
            /** @description True when the requested locale was unavailable and the English source value was returned. */
            localeFallback: boolean;
            name: string;
            description: string;
            /** @description Exact source-backed description before DB2 token resolution. */
            rawDescription: string;
            /** @description Display-ready description after resolving build-pinned DB2 value tokens. */
            resolvedDescription: string;
            /** @description present, missing, or unresolved; lets clients distinguish usable text from a source gap or unresolved template. */
            descriptionState: string;
            /** @description Raw, build-pinned source payload for the published entity version. */
            payload: {
                [key: string]: unknown;
            };
            /** @description Source-backed English and Russian fields. No synthetic translations are added. */
            localizations: {
                [key: string]: components["schemas"]["GameEntityLocalization"];
            };
            tooltip?: components["schemas"]["GameTooltip"];
            /** @description Source-backed media for the published entity build. Empty or absent when no publishable media exists. */
            media?: components["schemas"]["GameEntityMedia"][];
            iconName?: string;
            /** Format: uri */
            iconUrl?: string;
            quality?: number;
            /** Format: int64 */
            buildId?: number;
            /** Format: date-time */
            updatedAt: string;
        };
        GameEntityMedia: {
            /** @example icon */
            kind: string;
            /** @example icon */
            assetKey: string;
            /**
             * Format: uri
             * @description Cached URL when available, otherwise the verified remote asset URL.
             */
            url: string;
            /** @example blizzard_api */
            source: string;
            /** Format: uri */
            sourceUrl: string;
            /** @example en_US */
            locale: string;
            /** @example image/jpeg */
            mimeType: string;
            /** @enum {string} */
            cacheStatus: "remote" | "cached" | "blocked" | "failed";
            /** Format: int64 */
            fileDataId?: number;
            width?: number;
            height?: number;
            primary: boolean;
        };
        GameEntityTypeSummary: {
            type: string;
            label: string;
            description: string;
            group: string;
            iconSymbol: string;
            sortOrder: number;
            /** Format: int64 */
            count: number;
            /** Format: int64 */
            localizedCount: number;
            /** Format: int64 */
            describedCount: number;
            /** Format: int64 */
            tooltipCount: number;
            /** Format: int64 */
            iconCount: number;
            /** Format: int64 */
            relationshipCount: number;
            /** Format: date-time */
            coverageUpdatedAt: string;
        };
        GameEntitySummary: {
            /** Format: uuid */
            id: string;
            type: string;
            /** Format: int64 */
            externalId: number;
            slug: string;
            name: string;
            product?: string;
            /** @enum {string} */
            locale?: "en_US" | "ru_RU";
            localeFallback?: boolean;
            description?: string;
            iconName?: string;
            /** Format: uri */
            iconUrl?: string;
            quality?: number;
            itemLevel?: number;
            /** Format: int64 */
            buildId?: number;
            /** Format: date-time */
            updatedAt?: string;
            highlights?: components["schemas"]["GameEntityHighlight"][];
        };
        GameEntityHighlight: {
            key: string;
            value: string;
        };
        GameSitemapEntry: {
            /** Format: uuid */
            id: string;
            type: string;
            slug: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SummaryCursorPage: {
            nextCursor?: string;
            hasMore: boolean;
            /** Format: int64 */
            total?: number;
        };
        GameEntitySummaryPage: {
            data: components["schemas"]["GameEntitySummary"][];
            pagination: components["schemas"]["SummaryCursorPage"];
        };
        GameFieldCoverage: {
            product: string;
            /** Format: int64 */
            buildId: number;
            type: string;
            /** @enum {string} */
            locale: "en_US" | "ru_RU";
            field: string;
            source: string;
            /** Format: int64 */
            entityCount: number;
            /** Format: int64 */
            populatedCount: number;
            /** Format: int64 */
            unresolvedCount: number;
            /** Format: int64 */
            conflictCount: number;
            /** Format: date-time */
            refreshedAt: string;
        };
        GameSourcePolicy: {
            source: string;
            displayName: string;
            homepageUrl: string;
            termsUrl: string;
            licenseIdentifier: string;
            /** @enum {string} */
            commercialUseStatus: "allowed" | "restricted" | "permission_required" | "prohibited" | "unknown";
            /** @enum {string} */
            publicApiStatus: "allowed" | "restricted" | "permission_required" | "prohibited" | "unknown";
            /** @enum {string} */
            assetCachingStatus: "allowed" | "restricted" | "permission_required" | "prohibited" | "unknown";
            retentionDays?: number;
            attributionRequired: boolean;
            attributionText: string;
            /** Format: date-time */
            reviewedAt?: string;
            /** @enum {string} */
            reviewStatus: "pending" | "reviewed" | "expired" | "blocked";
            notes: string;
        };
        GameRelationType: {
            relation: string;
            label: string;
            description: string;
            inverseRelation?: string;
            allowedSourceTypes: string[];
            allowedTargetTypes: string[];
            attributeSchema: {
                [key: string]: unknown;
            };
            schemaVersion: number;
        };
        GameEntityRelationship: {
            /** @enum {string} */
            direction: "outgoing" | "incoming";
            relation: string;
            /** Format: int64 */
            buildId: number;
            attributes: {
                [key: string]: unknown;
            };
            entity: components["schemas"]["GameEntitySummary"];
        };
        GameEntityRelationshipPage: {
            data: components["schemas"]["GameEntityRelationship"][];
            pagination: components["schemas"]["CursorPage"];
        };
        GameEntityQualityCheck: {
            key: string;
            label: string;
            present: boolean;
            required: boolean;
            detail?: string;
        };
        GameEntitySource: {
            source: string;
            displayName: string;
            documents: number;
            /** Format: uri */
            sourceUrl?: string;
            /** Format: date-time */
            importedAt?: string;
        };
        GameEntityQuality: {
            /** Format: uuid */
            entityId: string;
            score: number;
            /** @enum {string} */
            status: "verified" | "partial" | "minimal";
            /** Format: int64 */
            buildId: number;
            buildNumber: number;
            buildVersion: string;
            /** Format: date-time */
            updatedAt: string;
            checks: components["schemas"]["GameEntityQualityCheck"][];
            confirmed: string[];
            missing: string[];
            sources: components["schemas"]["GameEntitySource"][];
        };
        GameEntityVersion: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            buildId: number;
            buildNumber: number;
            buildVersion: string;
            revision: number;
            name: string;
            description: string;
            sourceUrl: string;
            /** Format: date-time */
            observedAt: string;
        };
        GameEntityChange: {
            field: string;
            label: string;
            before?: unknown;
            after?: unknown;
            /** @enum {string} */
            changeType: "added" | "removed" | "changed";
        };
        GameEntityComparison: {
            from: components["schemas"]["GameEntityVersion"];
            to: components["schemas"]["GameEntityVersion"];
            changes: components["schemas"]["GameEntityChange"][];
        };
        GameTooltip: {
            plainText: string;
            blocks: {
                [key: string]: unknown;
            }[];
        };
        GameCategory: {
            /** Format: int64 */
            id: number;
            type: string;
            facet: string;
            slug: string;
            path: string;
            parentPath?: string;
            name: string;
            description?: string;
            /** Format: int64 */
            count: number;
            sortOrder: number;
        };
        CursorPage: {
            nextCursor?: string;
            hasMore: boolean;
            /** Format: int64 */
            total: number;
        };
        GameEntityPage: {
            data: components["schemas"]["GameEntity"][];
            pagination: components["schemas"]["CursorPage"];
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        APIError: {
            code: string;
            message: string;
        };
        AnalyticsPoint: {
            /** Format: date-time */
            hour: string;
            /** Format: int64 */
            events: number;
            /** Format: int64 */
            uniqueUsers: number;
        };
        AnalyticsOverview: {
            hours: number;
            /** Format: int64 */
            events: number;
            /** Format: int64 */
            uniqueUsers: number;
            /** Format: int64 */
            activeSubscriptions: number;
            series: components["schemas"]["AnalyticsPoint"][];
        };
        AnalyticsEvent: {
            /** Format: uuid */
            eventId?: string;
            eventName: string;
            /** Format: date-time */
            occurredAt?: string;
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            sessionId: string;
            path: string;
            /** @enum {string} */
            locale: "en" | "ru";
            /** Format: double */
            value?: number;
            properties?: {
                [key: string]: unknown;
            };
        };
        IngestEventsRequest: {
            events: components["schemas"]["AnalyticsEvent"][];
        };
        IngestEventsResponse: {
            accepted: number;
        };
        IndexNowRequest: {
            urls: string[];
        };
        QueuedResponse: {
            queued: boolean;
        };
    };
    responses: {
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Internal server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit exceeded. */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Catalog delivery is fail-closed because at least one contributing source lacks a current policy or explicit publication grant. */
        CatalogPublicationUnavailable: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Verified media is temporarily unavailable. */
        MediaUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Catalog authentication is required in private mode. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAPIIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API entry point. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIIndex"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    listGameProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supported products. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GameProduct"][];
                    };
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CatalogPublicationUnavailable"];
        };
    };
    listLibraryDatasets: {
        parameters: {
            query?: {
                product?: string;
                locale?: "en_US" | "ru_RU";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public library datasets backed by published catalog versions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LibraryDataset"][];
                    };
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CatalogPublicationUnavailable"];
        };
    };
    listGameEntityTypes: {
        parameters: {
            query?: {
                product?: string;
                locale?: "en_US" | "ru_RU";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity types with localized, tooltip and relationship coverage. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GameEntityTypeSummary"][];
                    };
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CatalogPublicationUnavailable"];
        };
    };
    listGameEntities: {
        parameters: {
            query?: {
                product?: string;
                type?: string;
                locale?: "en_US" | "ru_RU";
                q?: string;
                /** @description Taxonomy path. Selecting a parent includes all descendants. */
                category?: string;
                /** @description Opaque cursor from the previous response. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cursor-paginated game entities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameEntityPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CatalogPublicationUnavailable"];
        };
    };
    listGameEntitySummaries: {
        parameters: {
            query?: {
                product?: string;
                type?: string;
                /** @description Public library dataset slug. The server resolves its entity type and membership filters from the dataset registry. */
                dataset?: string;
                locale?: "en_US" | "ru_RU";
                q?: string;
                /** @description Taxonomy path. Selecting a parent includes all descendants. */
                category?: string;
                /** @description Repeatable taxonomy paths combined with AND semantics. Use one value per facet, for example class plus specialization plus equipment slot. */
                facet?: string[];
                /** @description Stable game item class identifier, for example 2 for weapons and 4 for armor. */
                itemClassId?: number;
                /** @description Minimum stored base item level. Applies to item records. */
                minItemLevel?: number;
                /** @description Maximum stored base item level. Applies to item records. */
                maxItemLevel?: number;
                /** @description Minimum character level required to use an item. */
                minRequiredLevel?: number;
                /** @description Maximum character level required to use an item. */
                maxRequiredLevel?: number;
                /** @description Opaque cursor from the previous response. */
                cursor?: string;
                limit?: number;
                /** @description Include an exact or cached total. Search totals may require an additional count query. */
                includeTotal?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cursor-paginated lightweight entity summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameEntitySummaryPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CatalogPublicationUnavailable"];
        };
    };
    listGameSitemapEntries: {
        parameters: {
            query: {
                product?: string;
                type: string;
                /** @description Zero, one, or two lowercase hexadecimal UUID prefix characters. */
                shard?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable entity URLs for one sitemap shard. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GameSitemapEntry"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CatalogPublicationUnavailable"];
        };
    };
    listGameCategories: {
        parameters: {
            query: {
                product?: string;
                type: string;
                locale?: "en_US" | "ru_RU";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hierarchical taxonomy with counts including descendants. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GameCategory"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CatalogPublicationUnavailable"];
        };
    };
    getGameEntity: {
        parameters: {
            query?: {
                locale?: "en_US" | "ru_RU";
                /** @description Optional public library dataset scope. Returns 404 when the entity is not a member. */
                dataset?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game entity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameEntity"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CatalogPublicationUnavailable"];
        };
    };
    listGameEntityRelationships: {
        parameters: {
            query?: {
                locale?: "en_US" | "ru_RU";
                direction?: "outgoing" | "incoming" | "both";
                /** @description Optional exact relation type such as owned_by, grants or obtained_from. */
                relation?: string;
                /** @description Opaque cursor from the previous response. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cursor-paginated relationships and related entity summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameEntityRelationshipPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CatalogPublicationUnavailable"];
        };
    };
    getGameEntityQuality: {
        parameters: {
            query?: {
                locale?: "en_US" | "ru_RU";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity quality report derived from stored catalog facts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameEntityQuality"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listGameEntityVersions: {
        parameters: {
            query?: {
                locale?: "en_US" | "ru_RU";
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GameEntityVersion"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getGameEntityComparison: {
        parameters: {
            query?: {
                locale?: "en_US" | "ru_RU";
                fromBuildId?: number;
                toBuildId?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Field-level comparison backed by stored versions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameEntityComparison"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listGameCoverage: {
        parameters: {
            query?: {
                product?: string;
                locale?: "en_US" | "ru_RU";
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coverage by entity type and field for the active build. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GameFieldCoverage"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CatalogPublicationUnavailable"];
        };
    };
    listGameSourcePolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source policy registry. This metadata is operational guidance, not legal advice. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GameSourcePolicy"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listGameRelationTypes: {
        parameters: {
            query?: {
                locale?: "en_US" | "ru_RU";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered relationship types and constraints. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GameRelationType"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CatalogPublicationUnavailable"];
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependencies are ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            /** @description A required dependency is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    getAnalyticsOverview: {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated product analytics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsOverview"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    ingestAnalyticsEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestEventsRequest"];
            };
        };
        responses: {
            /** @description Events accepted for async insertion. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestEventsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    submitIndexNow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexNowRequest"];
            };
        };
        responses: {
            /** @description IndexNow submission queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuedResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getCatalogMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Binary media object. */
            200: {
                headers: {
                    ETag?: string;
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Only GET and HEAD are supported. */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["MediaUnavailable"];
        };
    };
    executeGraphQL: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphQLRequest"];
            };
        };
        responses: {
            /** @description GraphQL response envelope. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphQLResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
}
