export type EnemyIntel = {
  summary: string;
  danger: string;
};

export type AbilityIntel = {
  effect: string;
  failure: string;
};

export const enemyIntel: Record<string, EnemyIntel> = {
  "Flashfrost Chillweaver": { summary: "Ледяной заклинатель. Создаёт щиты и атакует группу морозом.", danger: "Щит заметно затягивает бой, поэтому этого врага убивают одним из первых." },
  "Infused Whelp": { summary: "Маленький дракон, который быстро накапливает на танке эффект Cold Claws.", danger: "На 20 уровнях эффекта танк замерзает и не может действовать 5 секунд." },
  "Primalist Recruit": { summary: "Обычный боец ближнего боя без ключевой механики.", danger: "Не требует отдельной реакции, пока рядом живы более опасные враги." },
  "Deepstone Earthshaper": { summary: "Земляной заклинатель с опасными дальними атаками.", danger: "Его заклинания усиливают общий урон по группе — убить в числе первых." },
  "Earthbound Guardian": { summary: "Тяжёлый страж, наносящий сильные удары по танку и случайной цели.", danger: "Совпадение двух ударов может быстро убить игрока без защиты." },
  "Primal Juggernaut": { summary: "Крупный противник с ударом по танку и опасной зоной на земле.", danger: "Два таких врага одновременно создают главное опасное окно первого этажа." },
  "Defier Draghar": { summary: "Обязательный страж перед первым боссом.", danger: "Steel Barrage тяжело бьёт танка, а Blazing Rush оставляет опасную линию." },
  "Melidrussa Chillworn": { summary: "Первый босс подземелья. Управляет ледяной бурей и призывает дракончиков.", danger: "Во время Frost Overload группа должна быстро разрушить щит босса." },
  "Blazebound Destroyer": { summary: "Большой огненный элементаль с уроном по всей группе.", danger: "После смерти взрывается — все игроки должны заранее отойти." },
  "Primalist Cinderweaver": { summary: "Огненный заклинатель рядом с Destroyer.", danger: "Его заклинания нужно прерывать, чтобы не усиливать урон по группе." },
  "Scorchling": { summary: "Маленький огненный противник, опасный только в большой группе.", danger: "Собирается вместе с крупными врагами и погибает от массового урона." },
  Thunderhead: { summary: "Грозовой дракон, которого всегда разворачивают от команды.", danger: "Дыхание поражает область спереди, а Rolling Thunder нельзя снимать одновременно." },
  Flamegullet: { summary: "Огненный дракон, который становится опаснее после 50% здоровья.", danger: "На второй половине боя урон по всей группе быстро возрастает." },
  "Ashseer Flamelasher": { summary: "Огненный противник, усиливающий себя перед атакой.", danger: "Blaze of Glory нужно снять, иначе враг наносит значительно больше урона." },
  "Kokia Blazehoof": { summary: "Второй босс. Бросает огненные валуны и призывает дополнительных врагов.", danger: "Призванного Firestorm ставят рядом с боссом и быстро убивают." },
  "Blazebound Firestorm": { summary: "Дополнительный враг, которого призывает Кокия.", danger: "Blaze Volley наносит тяжёлый урон всей группе, если его не прервать." },
  "Storm Warrior": { summary: "Боец ближнего боя с круговым ударом Thunderous Stomp.", danger: "Игроки рядом должны отойти от врага во время удара." },
  "Flame Channeler": { summary: "Огненный заклинатель на лестнице к финальной зоне.", danger: "Flashfire нужно прервать — это его главная опасная атака." },
  "Tempest Channeler": { summary: "Грозовой заклинатель с дальними атаками.", danger: "Несколько одновременных Thunder Blast быстро создают опасный урон." },
  "Primal Thundercloud": { summary: "Призванное грозовое существо со щитом.", danger: "Его усиление нужно снять, а самого врага — быстро забрать танку." },
  "High Channeler Ryvati": { summary: "Последний сильный враг перед финальным боссом.", danger: "Shock Blast нельзя пропускать, а защитный щит нужно разрушить сразу." },
  Kyrakka: { summary: "Огненный дракон финального боя. Сначала атакует с воздуха.", danger: "Оставляет огонь на земле, поэтому свободного места постепенно становится меньше." },
  "Erkhart Stormvein": { summary: "Наземный противник финального боя, управляющий ветром и молниями.", danger: "Stormslam тяжело бьёт танка, а Winds of Change сдвигает игроков в огонь." },
};

export const abilityIntel: Record<string, AbilityIntel> = {
  "Ice Shield": { effect: "Создаёт на враге щит и мешает быстро его убить.", failure: "Если не прервать, бой затянется и группа получит больше урона." },
  "Cold Claws": { effect: "Накапливает на танке морозный негативный эффект.", failure: "На 20 уровнях танк замёрзнет и будет оглушён на 5 секунд." },
  Frostbolt: { effect: "Направленная морозная атака в одного игрока.", failure: "Пропущенные заклинания создают лишний урон, который придётся лечить." },
  "Tectonic Strike": { effect: "Очень сильный физический удар по танку.", failure: "Без заранее включённой защиты танк может погибнуть." },
  "Earthbound's Imprint": { effect: "Негативный эффект и последующий урон по выбранному игроку.", failure: "Игрок без личной защиты может не пережить следующий удар." },
  "Stone Missile": { effect: "Дальний каменный снаряд в случайного игрока.", failure: "Каждый пропуск добавляет ненужный урон по команде." },
  "Excavating Blast": { effect: "Создаёт опасную область и наносит урон группе.", failure: "Игроки в зоне получают тяжёлый урон; на повтор нужна защита группы." },
  "Crushing Smash": { effect: "Сильный удар по текущей цели врага — обычно по танку.", failure: "Танк без защиты может потерять большую часть здоровья." },
  "Steel Barrage": { effect: "Серия тяжёлых ударов по танку и периодический урон группе.", failure: "Танк должен держать защиту до полного окончания серии." },
  "Blazing Rush": { effect: "Враг разбегается по прямой к выбранному игроку.", failure: "Стоящие на линии получают урон; длинный разбег оставляет меньше места." },
  "Molten Steel": { effect: "Оставляет на площадке расплавленные опасные участки.", failure: "Касание наносит большой урон и мешает безопасно двигаться." },
  "Frigid Shard": { effect: "Прерываемая морозная атака босса по танку.", failure: "Пропуск создаёт тяжёлый удар, который можно полностью предотвратить." },
  Chillstorm: { effect: "Затягивает игроков к центру, затем отбрасывает наружу.", failure: "Центр бури наносит больше урона, а отбрасывание может толкнуть в ледяные мины." },
  "Frost Overload": { effect: "Босс закрывается щитом и всё сильнее повреждает всю группу.", failure: "Пока щит не разрушен, урон постоянно растёт и бой быстро становится смертельным." },
  Inferno: { effect: "Неизбежный огненный урон по всей группе.", failure: "Если команда входит в способность с низким здоровьем, игроки могут погибнуть." },
  "Fiery Blast": { effect: "Прерываемая огненная атака с большим уроном.", failure: "Пропуск создаёт опасный всплеск урона по выбранной цели." },
  Cinderbolt: { effect: "Быстрое огненное заклинание в случайного игрока.", failure: "Несколько пропусков подряд перегружают лечение." },
  Burnout: { effect: "Взрыв вокруг огненного врага в момент его смерти.", failure: "Игроки рядом получают очень большой урон — нужно заранее отойти." },
  "Storm Breath": { effect: "Широкое дыхание перед драконом.", failure: "Любой игрок перед драконом получает тяжёлый урон." },
  "Thunder Jaw": { effect: "Сильная атака дракона по танку.", failure: "Требует заранее включённой защиты танка." },
  "Rolling Thunder": { effect: "Два игрока получают снимаемый грозовой эффект.", failure: "Если снять оба эффекта одновременно, два взрыва наложатся друг на друга." },
  "Flame Breath": { effect: "Огненное дыхание перед драконом.", failure: "Стоящие перед врагом получают тяжёлый урон." },
  "Fire Maw": { effect: "Сильный огненный укус по танку.", failure: "Без защиты танк получает опасный одиночный удар." },
  "Molten Blood": { effect: "После 50% здоровья всё сильнее повреждает всю группу.", failure: "Затянутый бой во второй половине быстро исчерпывает лечение." },
  "Flaming Barrage": { effect: "Серия огненных атак по группе.", failure: "Останавливается контролем; полный канал создаёт слишком много урона." },
  "Blaze of Glory": { effect: "Усиливает огненного врага.", failure: "Если не снять усиление, его атаки становятся значительно опаснее." },
  "Ritual of Blazebinding": { effect: "Создаёт дополнительного огненного врага рядом с выбранным игроком.", failure: "Плохое место появления отдалит врага от босса и замедлит его убийство." },
  "Blaze Volley": { effect: "Прерываемое заклинание с уроном по всей группе.", failure: "Пропуск одновременно повреждает всех пяти игроков." },
  "Molten Boulder": { effect: "Большой валун катится по прямой, пока не столкнётся со стеной.", failure: "Игрок на пути получает тяжёлый урон и может погибнуть." },
  "Searing Blows": { effect: "Серия ударов по танку с нарастающим огненным эффектом.", failure: "Танк должен использовать защиту, а лекарь — быть готовым к росту урона." },
  "Thunderous Stomp": { effect: "Круговой удар вокруг Storm Warrior.", failure: "Игроки рядом с врагом получают урон, если не отойдут." },
  Flashfire: { effect: "Опасное прерываемое огненное заклинание.", failure: "Пропуск наносит большой урон выбранному игроку." },
  "Thunder Stomper": { effect: "Мощный удар и контроль рядом с врагом.", failure: "Нужно остановить оглушением или другим контролем." },
  "Thunder Blast": { effect: "Грозовая атака в случайного игрока.", failure: "Несколько одновременных заклинаний создают смертельный урон." },
  "Lightning Storm": { effect: "Неизбежный грозовой урон по всей группе.", failure: "Команде нужна общая защита и подготовленное лечение." },
  "Stormcloud Barrier": { effect: "Защитное усиление на грозовом враге.", failure: "Если не снять усиление, враг дольше живёт и продолжает атаковать." },
  "Tempest Stormshield": { effect: "Прочный щит, защищающий главную цель.", failure: "Весь урон нужно быстро направить в щит, иначе опасная фаза затянется." },
  "Shock Blast": { effect: "Главное прерываемое заклинание High Channeler Ryvati.", failure: "Пропуск наносит крайне высокий урон и может завершить попытку." },
  "Roaring Firebreath": { effect: "Широкий огненный конус перед Кираккой.", failure: "Игроки внутри области получают тяжёлый урон." },
  "Interrupting Cloudburst": { effect: "Взрыв, который наказывает игроков, продолжающих произносить заклинания.", failure: "Перед взрывом лекарь и атакующие заклинатели должны остановиться." },
  "Inferno Spit": { effect: "Негативный эффект, после которого под игроком остаётся огонь.", failure: "Огонь в центре площадки отнимет безопасное место у всей команды." },
  Stormslam: { effect: "Сильный удар по танку и снимаемый грозовой эффект.", failure: "Эффект увеличивает следующий грозовой урон и должен быть быстро снят." },
  "Winds of Change": { effect: "Сильный ветер сдвигает всех игроков по площадке.", failure: "Игроков может столкнуть в оставленный на земле огонь." },
};

export const abilitySource: Record<string, string> = {
  "Ice Shield": "Flashfrost Chillweaver",
  "Cold Claws": "Infused Whelp",
  Frostbolt: "Flashfrost Chillweaver",
  "Tectonic Strike": "Earthbound Guardian",
  "Earthbound's Imprint": "Earthbound Guardian",
  "Stone Missile": "Deepstone Earthshaper",
  "Excavating Blast": "Primal Juggernaut",
  "Crushing Smash": "Primal Juggernaut",
  "Steel Barrage": "Defier Draghar",
  "Blazing Rush": "Defier Draghar",
  "Molten Steel": "Defier Draghar",
  "Frigid Shard": "Melidrussa Chillworn",
  Chillstorm: "Melidrussa Chillworn",
  "Frost Overload": "Melidrussa Chillworn",
  Inferno: "Blazebound Destroyer / Firestorm",
  "Fiery Blast": "Blazebound Destroyer",
  Cinderbolt: "Primalist Cinderweaver",
  Burnout: "Blazebound Destroyer / Firestorm",
  "Storm Breath": "Thunderhead",
  "Thunder Jaw": "Thunderhead",
  "Rolling Thunder": "Thunderhead",
  "Flame Breath": "Flamegullet",
  "Fire Maw": "Flamegullet",
  "Molten Blood": "Flamegullet",
  "Flaming Barrage": "Ashseer Flamelasher",
  "Blaze of Glory": "Ashseer Flamelasher",
  "Ritual of Blazebinding": "Kokia Blazehoof",
  "Blaze Volley": "Blazebound Firestorm",
  "Molten Boulder": "Kokia Blazehoof",
  "Searing Blows": "Kokia Blazehoof",
  "Thunderous Stomp": "Storm Warrior",
  Flashfire: "Flame Channeler",
  "Thunder Stomper": "Storm Warrior",
  "Thunder Blast": "Tempest Channeler",
  "Lightning Storm": "Tempest Channeler / High Channeler Ryvati",
  "Stormcloud Barrier": "Primal Thundercloud",
  "Tempest Stormshield": "High Channeler Ryvati",
  "Shock Blast": "High Channeler Ryvati",
  "Roaring Firebreath": "Kyrakka",
  "Interrupting Cloudburst": "Erkhart Stormvein",
  "Inferno Spit": "Kyrakka",
  Stormslam: "Erkhart Stormvein",
  "Winds of Change": "Erkhart Stormvein",
};
