package graphqlapi

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/Gildra-Foundation/Gildra/backend/internal/catalog"
	"github.com/Gildra-Foundation/Gildra/backend/internal/graphqlapi/model"
	"github.com/google/uuid"
)

// GameProducts is the resolver for the gameProducts field.
func (r *queryResolver) GameProducts(ctx context.Context) ([]*model.GameProduct, error) {
	products, err := r.Catalog.Products(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.GameProduct, 0, len(products))
	for _, product := range products {
		result = append(result, toGraphQLProduct(product))
	}
	return result, nil
}

// LibraryDatasets is the resolver for the libraryDatasets field.
func (r *queryResolver) LibraryDatasets(ctx context.Context, product *string, locale *model.Locale) ([]*model.LibraryDataset, error) {
	productSlug := "wow"
	if product != nil {
		productSlug = *product
	}
	datasets, err := r.Catalog.LibraryDatasets(ctx, productSlug, localeValue(locale))
	if err != nil {
		return nil, err
	}
	result := make([]*model.LibraryDataset, 0, len(datasets))
	for _, dataset := range datasets {
		result = append(result, toGraphQLDataset(dataset))
	}
	return result, nil
}

// GameEntity is the resolver for the gameEntity field.
func (r *queryResolver) GameEntity(ctx context.Context, id string, locale *model.Locale) (*model.GameEntity, error) {
	entityID, err := uuid.Parse(id)
	if err != nil {
		return nil, errors.New("id must be a valid UUID")
	}
	entity, err := r.Catalog.Get(ctx, entityID, localeValue(locale))
	if errors.Is(err, catalog.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return toGraphQLEntity(entity), nil
}

// GameEntities is the resolver for the gameEntities field.
func (r *queryResolver) GameEntities(ctx context.Context, product *string, typeArg *string, locale *model.Locale, query *string, cursor *string, limit *int) (*model.GameEntityConnection, error) {
	params := catalog.ListParams{Locale: localeValue(locale), Limit: 20}
	if product != nil {
		params.Product = *product
	}
	if typeArg != nil {
		params.Type = *typeArg
	}
	if query != nil {
		params.Query = *query
	}
	if cursor != nil {
		params.Cursor = *cursor
	}
	if limit != nil {
		params.Limit = *limit
	}
	page, err := r.Catalog.List(ctx, params)
	if err != nil {
		return nil, err
	}
	nodes := make([]*model.GameEntity, 0, len(page.Entities))
	for _, entity := range page.Entities {
		nodes = append(nodes, toGraphQLEntity(entity))
	}
	pageInfo := &model.PageInfo{HasMore: page.HasMore}
	if page.NextCursor != "" {
		pageInfo.NextCursor = &page.NextCursor
	}
	return &model.GameEntityConnection{Nodes: nodes, PageInfo: pageInfo}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
