// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type GameEntity struct {
	ID                  string                    `json:"id"`
	Product             string                    `json:"product"`
	Type                string                    `json:"type"`
	ExternalID          string                    `json:"externalId"`
	Slug                string                    `json:"slug"`
	Locale              Locale                    `json:"locale"`
	ResolvedLocale      Locale                    `json:"resolvedLocale"`
	LocaleFallback      bool                      `json:"localeFallback"`
	Name                string                    `json:"name"`
	Description         string                    `json:"description"`
	RawDescription      string                    `json:"rawDescription"`
	ResolvedDescription string                    `json:"resolvedDescription"`
	Localizations       []*GameEntityLocalization `json:"localizations"`
	Tooltip             *GameTooltip              `json:"tooltip,omitempty"`
	Media               []*GameEntityMedia        `json:"media"`
	IconName            *string                   `json:"iconName,omitempty"`
	IconURL             *string                   `json:"iconUrl,omitempty"`
	Quality             *int                      `json:"quality,omitempty"`
	BuildID             *string                   `json:"buildId,omitempty"`
	Payload             map[string]any            `json:"payload"`
	UpdatedAt           time.Time                 `json:"updatedAt"`
}

type GameEntityConnection struct {
	Nodes    []*GameEntity `json:"nodes"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type GameEntityLocalization struct {
	Locale              Locale `json:"locale"`
	Name                string `json:"name"`
	Description         string `json:"description"`
	ResolvedDescription string `json:"resolvedDescription"`
}

type GameEntityMedia struct {
	Kind        string  `json:"kind"`
	AssetKey    string  `json:"assetKey"`
	URL         string  `json:"url"`
	Source      string  `json:"source"`
	SourceURL   string  `json:"sourceUrl"`
	Locale      string  `json:"locale"`
	MimeType    string  `json:"mimeType"`
	CacheStatus string  `json:"cacheStatus"`
	FileDataID  *string `json:"fileDataId,omitempty"`
	Width       *int    `json:"width,omitempty"`
	Height      *int    `json:"height,omitempty"`
	Primary     bool    `json:"primary"`
}

type GameEntityRelationship struct {
	Direction  RelationshipDirection `json:"direction"`
	Relation   string                `json:"relation"`
	BuildID    string                `json:"buildId"`
	Attributes map[string]any        `json:"attributes"`
	Entity     *GameEntitySummary    `json:"entity"`
}

type GameEntityRelationshipConnection struct {
	Nodes    []*GameEntityRelationship `json:"nodes"`
	PageInfo *PageInfo                 `json:"pageInfo"`
	Total    int                       `json:"total"`
}

type GameEntitySummary struct {
	ID         string  `json:"id"`
	Product    string  `json:"product"`
	Type       string  `json:"type"`
	ExternalID string  `json:"externalId"`
	Slug       string  `json:"slug"`
	Name       string  `json:"name"`
	IconName   *string `json:"iconName,omitempty"`
	IconURL    *string `json:"iconUrl,omitempty"`
}

type GameProduct struct {
	ID                   int        `json:"id"`
	Slug                 string     `json:"slug"`
	Name                 string     `json:"name"`
	BuildNumber          *int       `json:"buildNumber,omitempty"`
	BuildVersion         *string    `json:"buildVersion,omitempty"`
	Source               string     `json:"source"`
	SourceBuildNumber    *int       `json:"sourceBuildNumber,omitempty"`
	SourceBuildVersion   *string    `json:"sourceBuildVersion,omitempty"`
	SourceStatus         *string    `json:"sourceStatus,omitempty"`
	SourceCheckedAt      *time.Time `json:"sourceCheckedAt,omitempty"`
	EntityCount          int        `json:"entityCount"`
	PublishedEntityCount int        `json:"publishedEntityCount"`
	PublicRelease        bool       `json:"publicRelease"`
	Freshness            string     `json:"freshness"`
	FreshnessReason      string     `json:"freshnessReason"`
}

type GameTooltip struct {
	PlainText string           `json:"plainText"`
	Blocks    []map[string]any `json:"blocks"`
}

type LibraryDataset struct {
	Slug                   string     `json:"slug"`
	Product                string     `json:"product"`
	EntityType             string     `json:"entityType"`
	CategoryPath           string     `json:"categoryPath"`
	ItemClassID            *int       `json:"itemClassId,omitempty"`
	Group                  string     `json:"group"`
	IconSymbol             string     `json:"iconSymbol"`
	SortOrder              int        `json:"sortOrder"`
	Name                   string     `json:"name"`
	Description            string     `json:"description"`
	BuildVersion           *string    `json:"buildVersion,omitempty"`
	PreviewIconName        *string    `json:"previewIconName,omitempty"`
	PreviewImageURL        *string    `json:"previewImageUrl,omitempty"`
	EntityCount            int        `json:"entityCount"`
	LocalizedCount         int        `json:"localizedCount"`
	VerifiedLocalizedCount int        `json:"verifiedLocalizedCount"`
	TooltipCount           int        `json:"tooltipCount"`
	ImageCount             int        `json:"imageCount"`
	Applicability          string     `json:"applicability"`
	ApplicabilityReason    string     `json:"applicabilityReason"`
	Freshness              string     `json:"freshness"`
	FreshnessReason        string     `json:"freshnessReason"`
	CoverageUpdatedAt      *time.Time `json:"coverageUpdatedAt,omitempty"`
}

type PageInfo struct {
	NextCursor *string `json:"nextCursor,omitempty"`
	HasMore    bool    `json:"hasMore"`
}

type Query struct {
}

type Locale string

const (
	LocaleEnUs Locale = "en_US"
	LocaleRuRu Locale = "ru_RU"
)

var AllLocale = []Locale{
	LocaleEnUs,
	LocaleRuRu,
}

func (e Locale) IsValid() bool {
	switch e {
	case LocaleEnUs, LocaleRuRu:
		return true
	}
	return false
}

func (e Locale) String() string {
	return string(e)
}

func (e *Locale) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Locale(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Locale", str)
	}
	return nil
}

func (e Locale) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Locale) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Locale) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RelationshipDirection string

const (
	RelationshipDirectionBoth     RelationshipDirection = "both"
	RelationshipDirectionIncoming RelationshipDirection = "incoming"
	RelationshipDirectionOutgoing RelationshipDirection = "outgoing"
)

var AllRelationshipDirection = []RelationshipDirection{
	RelationshipDirectionBoth,
	RelationshipDirectionIncoming,
	RelationshipDirectionOutgoing,
}

func (e RelationshipDirection) IsValid() bool {
	switch e {
	case RelationshipDirectionBoth, RelationshipDirectionIncoming, RelationshipDirectionOutgoing:
		return true
	}
	return false
}

func (e RelationshipDirection) String() string {
	return string(e)
}

func (e *RelationshipDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RelationshipDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RelationshipDirection", str)
	}
	return nil
}

func (e RelationshipDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RelationshipDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RelationshipDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
