import type { RouteText } from "./midnightRaidRoutes";

export type AbilityCounter = "kick" | "stop" | "dodge" | "los" | "purge" | "break" | "defensive" | "scripted";

export type RaidRouteAbilityIntel = {
  icon: string;
  caster: RouteText;
  counter: AbilityCounter;
  shape: RouteText;
  control: RouteText;
  tank: RouteText;
  healer: RouteText;
  damage: RouteText;
};

const icon = (spellId: number) => `/assets/wow/raids/midnight/trash-spells/${spellId}.jpg`;
const tx = (ru: string, en: string): RouteText => ({ ru, en });

export const routeAbilityIntel: Record<number, RaidRouteAbilityIntel> = {
  1228330: {
    icon: icon(1228330),
    caster: tx("Призыватель Бездны", "Abyssal Caller"),
    counter: "kick",
    shape: tx("Одиночный направленный каст в текущую цель. Зоны на полу нет: урон проходит в момент завершения полосы применения.", "A single-target cast into the current target. There is no ground zone; damage lands when the cast bar completes."),
    control: tx("Прерывается обычным киком. После завершения не уклоняется, не парируется и не блокируется — остановить нужно до конца каста.", "Interruptible with a standard interrupt. Once completed it cannot be dodged, parried, or blocked; stop it before the cast finishes."),
    tank: tx("Держите Призывателя в мили и не уводите его из радиуса кика.", "Keep the Caller in melee and within interrupt range."),
    healer: tx("Если каст прошел, немедленно поднимите его цель; следующий болт может добить игрока.", "If a cast gets through, immediately recover its target before the next bolt."),
    damage: tx("Первый и второй кик назначьте заранее; не перебивайте друг друга одновременно.", "Pre-assign the first and second interrupts and never overlap them."),
  },
  1228345: {
    icon: icon(1228345),
    caster: tx("Освобожденный призрак", "Unbound Wraith"),
    counter: "purge",
    shape: tx("Заметное фиолетовое усиление на самом призраке: скорость атак возрастает на 25%, передвижения — на 50%.", "A visible purple self-buff on the Wraith: 25% haste and 50% movement speed."),
    control: tx("Снимается пуржем или кражей заклинания. Уклоняться не от чего; если снять нечем, зафиксируйте врага оглушением или корнями.", "Purge or Spellsteal it. There is nothing to dodge; if no purge is available, lock the enemy down with a stun or root."),
    tank: tx("Не гонитесь за ускоренным призраком через рейд — остановитесь и верните его провокацией.", "Do not chase an accelerated Wraith through the raid; hold position and taunt it back."),
    healer: tx("Ожидайте учащенный физический урон по танку, пока усиление активно.", "Expect faster physical hits on the tank while the buff remains."),
    damage: tx("Снимите усиление сразу; это важнее дополнительного урона в первые секунды.", "Remove the buff immediately; it is worth more than extra opening damage."),
  },
  1230690: {
    icon: icon(1230690),
    caster: tx("Обскурион-облитератор", "Obscurion Obliterator"),
    counter: "stop",
    shape: tx("Цели поднимаются в темные сферы над землей, затем падают вниз. Опасность находится вокруг отмеченных игроков, поэтому им нельзя стоять вместе.", "Targets are lifted inside dark spheres and then slammed down. The danger follows marked players, so they must not overlap."),
    control: tx("После захвата блок и уклонение не помогают. Если Облитератор поддается контролю — сбейте начало оглушением; иначе разойдитесь минимум на 6 метров.", "Block and dodge do not help after the lift. If the Obliterator is controllable, stun the start; otherwise spread at least six yards."),
    tank: tx("Разверните Облитераторов от рейда и не собирайте их поверх дальних игроков.", "Face the Obliterators away and never stack them on ranged players."),
    healer: tx("Подготовьте быстрое групповое лечение к моменту падения сфер.", "Time quick raid healing for the moment the spheres slam down."),
    damage: tx("При сфере прекращайте сближение: каждый занимает собственный сектор и возвращается после падения.", "When spheres appear, stop collapsing; take separate sectors and return after the slam."),
  },
  1236497: {
    icon: icon(1236497),
    caster: tx("Страж террасы", "Terrace Watcher"),
    counter: "dodge",
    shape: tx("Длинный широкий конус от головы Стража в направлении текущей цели; наносит урон каждую секунду в течение 9 секунд.", "A long, wide cone from the Watcher's head toward its current target, ticking every second for nine seconds."),
    control: tx("Не прерывается и не должен танковаться лицом в рейд. Единственный надежный ответ — выйти за спину или за боковую грань конуса.", "Not interruptible and must never face the raid. The reliable response is to move behind it or beyond the cone's side edge."),
    tank: tx("До начала дыхания направьте голову к наружной стене и не поворачивайте моба все 9 секунд.", "Before the breath starts, face the head into the outer wall and hold it still for all nine seconds."),
    healer: tx("Лечите танка из бокового сектора; не пересекайте конус ради дистанции.", "Heal the tank from the side and never cross the cone just to gain range."),
    damage: tx("Мили проходят строго за спину, дальние делают один шаг к боковой стене — не бегите перед мордой.", "Melee move directly behind; ranged step toward a side wall and never cross in front of the head."),
  },
  1236560: {
    icon: icon(1236560),
    caster: tx("Блинки", "Blinky"),
    counter: "defensive",
    shape: tx("Неизбежная круговая волна радиусом 60 метров вокруг Блинки, поражающая весь рейд и отбрасывающая назад.", "An unavoidable 60-yard radial wave around Blinky that hits and knocks the entire raid back."),
    control: tx("Не уклоняется и не блокируется щитом. Переживается личной защитой; отбрасывание нейтрализуется правильным положением спиной к внутренней стене.", "Cannot be dodged or shield-blocked. Survive with personal defensives and neutralize the knockback by putting the inner wall behind you."),
    tank: tx("Поставьте Блинки так, чтобы внутренний бортик был за спиной рейда, а внешний край — перед ним.", "Position Blinky so the inner railing is behind the raid and the outer drop is in front."),
    healer: tx("Начните групповое лечение до завершения топота; внешний сейв отдайте игроку без личной защиты.", "Begin raid healing before the stomp completes and give an external to a player without a personal."),
    damage: tx("За секунду до удара прекратите перемещение, прижмитесь к внутренней стене и нажмите личный сейв.", "One second before impact, stop moving, hug the inner wall, and use a personal defensive."),
  },
  1247054: {
    icon: icon(1247054),
    caster: tx("Небесный исполин", "Celestial Behemoth"),
    counter: "dodge",
    shape: tx("Локальный электрический всплеск радиусом 8 метров вокруг точки удара. Несколько целей могут перекрыть зоны друг на друга.", "A local eight-yard lightning burst around the impact point. Multiple targets can overlap their zones."),
    control: tx("Не пытайтесь блокировать природный урон. Разнесите круги веером и выйдите из чужого радиуса до срабатывания.", "Do not try to block the Nature damage. Fan the circles out and leave every other target's radius before they detonate."),
    tank: tx("Оставьте дальним свободную внешнюю половину кольца и не двигайте Исполина через их круги.", "Reserve the outer half of the ring for ranged and never drag the Behemoth through their circles."),
    healer: tx("Следите за игроками на дальнем краю; не стойте в одном секторе со вторым лекарем.", "Watch players on the far edge and avoid sharing a sector with another healer."),
    damage: tx("Отмеченные уходят на 8+ метров друг от друга; не пересекайте центр с кругом.", "Marked players separate by 8+ yards and never cross center with a circle."),
  },
  1247056: {
    icon: icon(1247056),
    caster: tx("Небесный исполин", "Celestial Behemoth"),
    counter: "defensive",
    shape: tx("Пассивное электричество на щупальцах: каждая успешная атака Исполина добавляет природный урон по танку.", "Passive electricity on the tendrils: every successful Behemoth attack adds Nature damage to the tank."),
    control: tx("Каста и зоны нет — прерывать или уклоняться невозможно. Снижается активной защитой танка и внешними сейвами лекарей.", "There is no cast or ground zone, so it cannot be interrupted or dodged. Mitigate it with tank cooldowns and healer externals."),
    tank: tx("Не оставляйте окно без активной защиты; сильный сейв держите на вторую половину здоровья.", "Maintain active mitigation without gaps and save a major cooldown for the second half."),
    healer: tx("Поставьте внешний сейв между защитными способностями танка, а не поверх них.", "Place an external between the tank's own cooldowns instead of overlapping them."),
    damage: tx("Не стойте перед Исполином и быстро убейте малых медуз, чтобы снять лишнюю нагрузку с лекарей.", "Stay out of the front and quickly kill small jellyfish to reduce healer pressure."),
  },
  1251405: {
    icon: icon(1251405),
    caster: tx("Мракозария Вечный Рассвет", "Voidlight Everdawn"),
    counter: "scripted",
    shape: tx("Сценарный призыв на порогах здоровья: вокруг Мракозарии открываются порталы, из которых выходят Темные порождения.", "A scripted health-threshold summon: portals open around Everdawn and release Darkspawn."),
    control: tx("Сам призыв не блокируется и не снимается. Контролируйте уже появившихся существ массовым оглушением, немотой и притягиванием.", "The summon itself cannot be blocked or dispelled. Control spawned enemies with AoE stuns, silences, and grips."),
    tank: tx("Сведите каждую волну под Мракозарию; не позволяйте существам закрепиться на лекарях.", "Drag every wave beneath Everdawn and keep summons off the healers."),
    healer: tx("Стойте ближе к танку перед порогом здоровья, чтобы призывы не растягивали пак по арене.", "Move closer to the tank before each health threshold so summons do not spread the pack."),
    damage: tx("Сохраните массовый контроль и урон на порталы; ближайшее к лекарю существо получает череп.", "Save AoE control and burst for portals; skull anything closest to a healer."),
  },
  1255702: {
    icon: icon(1255702),
    caster: tx("Стойкий темный страж", "Shadowguard Stalwart"),
    counter: "purge",
    shape: tx("Темный магический щит появляется на союзниках Стража и поглощает большой объем входящего урона.", "A dark magic shield appears on the Stalwart's allies and absorbs a large amount of incoming damage."),
    control: tx("Щит снимается очищением вражеской магии. Если пуржа нет, переключитесь и разбейте поглощение прямым уроном.", "Purge the enemy magic effect. If no purge is available, swap and break the absorb with direct damage."),
    tank: tx("Держите защищенные цели рядом, чтобы бойцы не теряли урон на перебежках.", "Keep shielded targets together so damage players do not lose uptime."),
    healer: tx("Щит не требует лекарского диспела — не тратьте снятие отрицательных эффектов с союзников.", "This is an enemy buff, not a friendly debuff; do not waste a healer dispel."),
    damage: tx("Пуржер снимает щит мгновенно; без пуржа весь рейд переключается на одну защищенную цель.", "Assigned purge removes it immediately; without one, the raid focuses one shielded target at a time."),
  },
  1258601: {
    icon: icon(1258601),
    caster: tx("Гладий Слаурос", "Gladius Slauros"),
    counter: "dodge",
    shape: tx("Слаурос несколько раз рубит широкий конус прямо перед собой. Каждый повтор поражает всю переднюю полусферу.", "Slauros repeatedly cleaves a wide cone directly in front of himself. Every repeat hits the entire forward arc."),
    control: tx("Не полагайтесь на блок: танк может смягчить физический удар, но для рейда надежно только выйти за спину.", "Do not rely on block: the tank may mitigate the physical hit, but moving behind is the only reliable raid response."),
    tank: tx("Замрите на месте и не доворачивайте Слауроса за игроками до окончания серии.", "Hold perfectly still and never rotate Slauros toward players until the sequence ends."),
    healer: tx("Стойте сбоку или сзади; лечите возможную ошибку, не заходя в переднюю дугу.", "Stand at the side or rear and heal mistakes without entering the frontal arc."),
    damage: tx("Увидели разворот корпуса — сразу за спину. Не перебегайте через переднюю часть даже после первого взмаха.", "When his body turns, move behind immediately and do not cross the front after the first swing."),
  },
  1258621: {
    icon: icon(1258621),
    caster: tx("Блинки", "Blinky"),
    counter: "scripted",
    shape: tx("Короткая мгновенная телепортация Блинки на другую точку платформы; самостоятельного урона не наносит.", "A short instant teleport to another point on the platform; the blink itself deals no damage."),
    control: tx("Не прерывается. Не бегите за ним через край платформы — танк возвращает позицию провокацией и перемещением.", "Not interruptible. Do not chase across the platform edge; the tank restores position with taunt and movement."),
    tank: tx("Сразу заберите цель и приведите обратно к внутренней стене до следующего топота.", "Taunt immediately and return it to the inner wall before the next stomp."),
    healer: tx("Сместитесь к центру, чтобы не потерять танка по дистанции после телепортации.", "Shift toward center so the tank does not leave healing range after the blink."),
    damage: tx("Остановитесь и дождитесь позиции танка; не разворачивайте Блинки случайной провокацией.", "Pause and wait for the tank's position; never rotate Blinky with a stray taunt."),
  },
  1258624: {
    icon: icon(1258624),
    caster: tx("Блинки", "Blinky"),
    counter: "stop",
    shape: tx("Круговая волна страха радиусом 30 метров. После завершения каста игроки теряют управление на 6 секунд.", "A 30-yard radial fear. When the cast completes, players lose control for six seconds."),
    control: tx("Сбивайте жестким контролем: оглушением, дезориентацией или другим назначенным стопом. Щит и блок не предотвращают страх.", "Stop it with hard crowd control: stun, disorient, or another assigned stop. Shield block does not prevent the fear."),
    tank: tx("Держите Блинки в отмеченной точке и отдайте первый надежный стоп.", "Hold Blinky on the mark and take the first reliable stop."),
    healer: tx("Если стоп сорван, заранее поставьте защиту на рейд: во время страха никто не сможет нажать личный сейв.", "If the stop is missed, pre-place raid protection because players cannot use personals while feared."),
    damage: tx("Назначьте второй и третий стоп по именам; не тратьте их на малых существ перед воем.", "Assign the second and third stops by name and do not spend them on adds before the howl."),
  },
  1258656: {
    icon: icon(1258656),
    caster: tx("Страж террасы", "Terrace Watcher"),
    counter: "dodge",
    shape: tx("На нескольких игроках появляется персональная зона радиусом 7 метров, которая каждую секунду бьет находящихся рядом союзников 8 секунд.", "Several players gain personal seven-yard zones that damage nearby allies every second for eight seconds."),
    control: tx("Эффект не блокируется. Отмеченные расходятся и сохраняют дистанцию 7+ метров до полного исчезновения метки.", "The effect cannot be blocked. Marked players spread 7+ yards and stay separated until the marker fully expires."),
    tank: tx("Не ведите Стража к отмеченным игрокам; оставьте им свободные внешние углы.", "Do not drag the Watcher toward marked players; leave the outer corners free."),
    healer: tx("Каждому отмеченному требуется точечное лечение; не собирайте их ради группового исцеления.", "Spot-heal every marked player and do not collapse them for AoE healing."),
    damage: tx("Идите к ближайшему свободному краю, не пересекайте центр и не возвращайтесь до исчезновения ауры.", "Take the nearest open edge, avoid center, and do not return until the aura disappears."),
  },
  1270212: {
    icon: icon(1270212),
    caster: tx("Небесный исполин", "Celestial Behemoth"),
    counter: "los",
    shape: tx("Круговая космическая волна поражает и отбрасывает каждого, кто видит Исполина в момент срабатывания.", "A radial Cosmic wave damages and knocks back every player with line of sight to the Behemoth."),
    control: tx("Не блокируется и не уклоняется обычным движением. Полностью контрится разрывом линии видимости за внутренней колонной.", "Cannot be blocked or sidestepped normally. Counter it by fully breaking line of sight behind an inner pillar."),
    tank: tx("Подведите Исполина достаточно близко к колонне и спрячьтесь последним, не разворачивая его в рейд.", "Keep the Behemoth close enough to a pillar and hide last without rotating it into the raid."),
    healer: tx("Проверьте игроков, которые опоздали за укрытие; готовьте мгновенное лечение после волны.", "Watch for late players and prepare instant recovery after the wave."),
    damage: tx("Уберите Исполина из поля зрения полностью: одной ногой за колонной недостаточно.", "Remove the Behemoth fully from view; standing halfway behind a pillar is not enough."),
  },
  1272971: {
    icon: icon(1272971),
    caster: tx("Темный скиталец", "Dark Drifter"),
    counter: "defensive",
    shape: tx("Пассивное усиление щупалец: каждая успешная атака скитальца наносит дополнительный теневой урон его цели.", "A passive tendril enhancement: every successful Drifter attack deals bonus Shadow damage to its target."),
    control: tx("Прерывать нечего. Урон снижается броней и защитой танка; оглушение уменьшает число успешных атак.", "There is no cast to interrupt. Tank mitigation reduces the damage, while stuns reduce the number of landed attacks."),
    tank: tx("Соберите всех четырех лицом в стену и держите активную защиту до смерти второго скитальца.", "Stack all four facing a wall and maintain active mitigation until the second Drifter dies."),
    healer: tx("Дайте внешний сейв на сборку пака, до того как танк получит четыре одновременных удара.", "Apply an external while the pack is being stacked, before four attacks land together."),
    damage: tx("Дайте массовое оглушение после сборки и убивайте цели равномерным массовым уроном.", "AoE stun once stacked and burn them evenly with cleave."),
  },
  1274846: {
    icon: icon(1274846),
    caster: tx("Пожирающий темный заклинатель", "Devouring Darkcaller"),
    counter: "defensive",
    shape: tx("Несколько направленных темных снарядов выбирают разных игроков и наносят урон при попадании; безопасной зоны на полу нет.", "Several targeted dark missiles select different players and deal damage on impact; there is no safe ground zone."),
    control: tx("После выбора целей снаряды не уклоняются и не блокируются. Используйте личную защиту и не накладывайте дополнительный урон от соседних механик.", "Once targets are chosen, missiles cannot be dodged or blocked. Use personals and avoid overlapping other mechanics."),
    tank: tx("Не двигайте пак во время залпа: рейду нужен предсказуемый сектор для рассредоточения.", "Hold the pack still during the barrage so the raid has predictable spread space."),
    healer: tx("Подготовьте мгновенное лечение нескольких целей и групповую защиту на совпадение со щитами.", "Prepare multi-target instant healing and a raid defensive if it overlaps shields."),
    damage: tx("Разойдитесь, нажмите личный сейв и продолжайте фокус Темного заклинателя.", "Spread, use a personal, and keep focusing the Darkcaller."),
  },
  1281453: {
    icon: icon(1281453),
    caster: tx("Гладий Моринас", "Gladius Morinas"),
    counter: "dodge",
    shape: tx("Вокруг Моринаса и отмеченных точек появляются темные разрывы, которые пульсируют каждые 3 секунды.", "Dark ruptures appear around Morinas and marked locations, pulsing every three seconds."),
    control: tx("Не прерывается и не блокируется. Выйдите из темной области до следующего импульса и оставляйте разрывы только по краям.", "Not interruptible or blockable. Leave the dark area before its next pulse and drop every rupture at the edge."),
    tank: tx("Держите Моринаса в центре прохода и не заводите его в уже лежащий разрыв.", "Keep Morinas in the passage center and never drag him into an existing rupture."),
    healer: tx("Лечите цель во время отхода к краю; не стойте между ней и безопасным сектором.", "Heal the target while it moves to the edge and never block its path to safety."),
    damage: tx("С меткой идите к ближайшему краю, дождитесь появления разрыва и сразу возвращайтесь по чистой линии.", "With the marker, move to the nearest edge, wait for the rupture, then return along a clean lane."),
  },
  1281525: {
    icon: icon(1281525),
    caster: tx("Разрушитель Бездны Троггар", "Voidbreaker Throggar"),
    counter: "dodge",
    shape: tx("Постоянный круговой вихрь тени и пламени вплотную вокруг Троггара, наносящий урон каждую секунду.", "A persistent point-blank Shadowflame whirlwind around Throggar that deals damage every second."),
    control: tx("Каст не нужно блокировать: все, кроме танка, немедленно выходят за внешнюю границу вихря. Танку — сильная защита.", "Do not try to block the cast: everyone except the tank exits beyond the whirlwind edge immediately. Tank uses heavy mitigation."),
    tank: tx("Медленно ведите Троггара по краю двора, не проводя вихрь через рейд.", "Walk Throggar slowly along the courtyard edge without sweeping the whirlwind through the raid."),
    healer: tx("Держите танка на максимальной безопасной дистанции и лечите игроков, которые поздно вышли.", "Heal the tank from maximum safe range and recover anyone who left late."),
    damage: tx("Мили разрывают дистанцию сразу; дальние не срезают путь через круг ради позиции.", "Melee disengage immediately; ranged never cut through the circle for position."),
  },
  1281528: {
    icon: icon(1281528),
    caster: tx("Разрушитель Бездны Троггар", "Voidbreaker Throggar"),
    counter: "break",
    shape: tx("На Троггаре появляется яркая смешанная пепельно-фиолетовая сфера, полностью поглощающая входящий урон.", "A bright ash-purple sphere forms around Throggar and absorbs incoming damage."),
    control: tx("Не рассчитывайте на обычный диспел: щит нужно разбить прямым уроном. Все атакующие немедленно переключаются в поглощение.", "Do not rely on a standard dispel; break the absorb with direct damage. Every damage player swaps immediately."),
    tank: tx("Стабилизируйте позицию Троггара, чтобы бойцы не теряли время на перемещение во время щита.", "Hold Throggar still so damage players lose no time to movement during the shield."),
    healer: tx("Щит продлевает опасную фазу; держите лечение танка до полного разрушения сферы.", "The shield extends the dangerous window; maintain tank healing until it breaks."),
    damage: tx("Отдайте сильные способности в щит; не сохраняйте их ради полосы здоровья под ним.", "Commit burst cooldowns into the shield and do not save them for the health bar beneath it."),
  },
  1281532: {
    icon: icon(1281532),
    caster: tx("Разрушитель Бездны Троггар", "Voidbreaker Throggar"),
    counter: "dodge",
    shape: tx("Троггар фиксирует одного игрока, затем прыгает в его точку и поражает круг радиусом 10 метров с отбрасыванием.", "Throggar locks onto one player, then leaps to that location and hits a ten-yard knockback circle."),
    control: tx("Сам прыжок не блокируется. Цель уносит круг в пустой угол, остальные заранее освобождают вокруг нее 10 метров.", "The leap cannot be blocked. The target carries the impact to an empty corner while everyone else clears ten yards around them."),
    tank: tx("После приземления сразу верните Троггара к отмеченной стене и отверните от рейда.", "After landing, immediately return Throggar to the marked wall and face him away."),
    healer: tx("Держите цель прыжка полной по здоровью и лечите ее на ходу.", "Keep the leap target healthy and heal them while they move."),
    damage: tx("Если вы цель — идите в свободный угол, не бегите вдоль группы. Остальные не преследуют босса до удара.", "If targeted, move to an empty corner, not along the group. Everyone else waits for impact before chasing."),
  },
  1281728: {
    icon: icon(1281728),
    caster: tx("Гладий Слаурос", "Gladius Slauros"),
    counter: "dodge",
    shape: tx("Прямые дорожки разрывов идут по полу от Слауроса и отбрасывают каждого, кого пересекают.", "Straight rupture lanes travel across the floor from Slauros and knock back anyone they cross."),
    control: tx("Не прерывается и не блокируется. Сделайте один шаг поперек линии в соседнюю чистую дорожку; не бегите вдоль разрыва.", "Not interruptible or blockable. Sidestep across the line into a clear lane and never run along the rupture."),
    tank: tx("Не перемещайте Слауроса вслед за уклоняющимся рейдом — направление линий должно оставаться предсказуемым.", "Do not move Slauros with the dodging raid; keep lane directions predictable."),
    healer: tx("Стойте между двумя возможными линиями и берегите мгновенное лечение на задетого игрока.", "Stand between likely lanes and save instant healing for anyone clipped."),
    damage: tx("Сначала пересеките линию под прямым углом, затем возвращайтесь за спину босса.", "Cross the line at a right angle first, then return behind the boss."),
  },
  1282010: {
    icon: icon(1282010),
    caster: tx("Пожирающий темный заклинатель", "Devouring Darkcaller"),
    counter: "kick",
    shape: tx("Длинная полоса каста над Темным заклинателем; после завершения рядом появляются дополнительные существа Бездны.", "A long cast bar above the Darkcaller; additional Void creatures appear nearby when it completes."),
    control: tx("Прерывайте обычным киком. Если кик недоступен, резервный игрок сбивает каст оглушением или немотой.", "Use a standard interrupt. If no interrupt is ready, the backup player stops it with a stun or silence."),
    tank: tx("Держите заклинателя в радиусе всех назначенных прерываний и не прячьте его за крупными врагами.", "Keep the Darkcaller inside every assigned interrupt range and do not hide it behind large enemies."),
    healer: tx("Если каст прошел, приблизьтесь к танку и приготовьте контроль существ, которые выберут вас целью.", "If it completes, move toward the tank and prepare control for summons that target you."),
    damage: tx("Это абсолютный первый кик. Следите за своей очередью, даже если другой опасный спелл начинается одновременно.", "This is the absolute first interrupt priority. Hold your assigned order even if another dangerous cast starts."),
  },
  1282201: {
    icon: icon(1282201),
    caster: tx("Гладий Слаурос", "Gladius Slauros"),
    counter: "scripted",
    shape: tx("Постоянная темная аура на Слауросе отражает 50% всего наносимого урона обратно атакующему.", "A persistent dark aura on Slauros reflects 50% of all incoming damage back to the attacker."),
    control: tx("Не снимается пуржем и не пробивается уроном. Единственный контрприем — сначала убить Ненасытникуса и Салхадаара.", "Cannot be purged or burned through. The only counter is to defeat Vorasius and Salhadaar first."),
    tank: tx("Не начинайте бой, пока аура активна; подтвердите смерть обоих боссов крыльев.", "Do not engage while the aura is active; confirm both wing bosses are dead."),
    healer: tx("Не пытайтесь компенсировать отражение лечением — остановите атаку рейда и смените маршрут.", "Do not try to heal through the reflection; stop raid damage and change route."),
    damage: tx("Полностью прекратите атаки при активной ауре, включая периодический урон и питомцев.", "Stop all attacks while the aura remains, including damage-over-time effects and pets."),
  },
  1283465: {
    icon: icon(1283465),
    caster: tx("Разрыв Бездны Моринаса", "Morinas's Void Rupture"),
    counter: "dodge",
    shape: tx("Стационарная темная зона на полу пульсирует по ближайшим игрокам каждые 3 секунды.", "A stationary dark ground zone pulses into nearby players every three seconds."),
    control: tx("Зону нельзя прервать, рассеять или заблокировать. Просто покиньте ее радиус до следующего импульса.", "The zone cannot be interrupted, dispelled, or blocked. Leave its radius before the next pulse."),
    tank: tx("Не ставьте Моринаса поверх разрыва: это заставит ближних бойцов потерять позицию.", "Never place Morinas on a rupture; doing so denies melee uptime."),
    healer: tx("Игрок, оставшийся в зоне на второй импульс, требует немедленной защиты и лечения.", "Anyone remaining for a second pulse needs immediate protection and healing."),
    damage: tx("Не пересекайте темную границу даже после первого тика; обойдите зону по чистой стороне.", "Do not cross the dark boundary after the first tick; go around via the clear side."),
  },
};

export const routeEnemyIcons: Record<number, string> = {
  240545: icon(1228345),
  240548: icon(1228330),
  240549: icon(1230690),
  240554: icon(1258621),
  240831: icon(1251405),
  240857: icon(1251405),
  240864: icon(1258624),
  243827: icon(1247054),
  250778: icon(1272971),
  250802: icon(1281525),
  250803: icon(1281453),
  251239: icon(1255702),
  252066: icon(1258601),
  252067: icon(1236497),
  256598: icon(1270212),
  259918: icon(1282010),
};

export function getRouteAbilityIntel(spellId: number) {
  return routeAbilityIntel[spellId];
}
