import type { LocalizedText } from "./midnightRaidTactics";

export type VoidspireMechanicTag =
  | "DODGE"
  | "INTERRUPT"
  | "STOP"
  | "PURGE"
  | "DISPEL_MAGIC"
  | "SOAK"
  | "SPREAD"
  | "STACK"
  | "MOVE"
  | "TANK_SWAP"
  | "DEFENSIVE"
  | "HARD_CC"
  | "TARGET_PRIORITY";

export type VoidspireMechanic = {
  id: string;
  name: LocalizedText;
  tags: VoidspireMechanicTag[];
  who: LocalizedText;
  action: LocalizedText;
  position: LocalizedText;
  timing: LocalizedText;
  failure: LocalizedText;
  difficulty: LocalizedText;
  spell?: { id: number; icon: string };
};

export type VoidspireBossGuide = {
  sourceUrl: string;
  sourceUpdatedAt: string;
  checkedAt: string;
  mechanics: VoidspireMechanic[];
};

const l = (ru: string, en: string): LocalizedText => ({ ru, en });
const spell = (id: number) => ({ id, icon: `/assets/wow/raids/midnight/spells/${id}.jpg` });

export const voidspireMechanicGuides: Record<string, VoidspireBossGuide> = {
  "imperator-averzian": {
    sourceUrl: "https://www.icy-veins.com/wow/imperator-averzian-raid-guide",
    sourceUpdatedAt: "2026-05-19",
    checkedAt: "2026-09-14",
    mechanics: [
      {
        id: "umbral-collapse",
        name: l("Темный коллапс", "Umbral Collapse"),
        tags: ["SOAK", "MOVE", "TARGET_PRIORITY"],
        who: l("Весь рейд; направление задает танк или рейд-лид", "Whole raid; direction is called by the tank or raid lead"),
        action: l("Вместе занесите два последовательных замачивания на двух выбранных ваятелей Бездны. Третий адд создаст портал.", "Move both consecutive group soaks onto the two called Voidshapers. The third add creates the portal."),
        position: l("Внутри выбранной клетки 3×3, прямо на нужном адде", "Inside the called 3×3 tile, directly on the chosen add"),
        timing: l("Два раза подряд в основной фазе", "Twice in succession during the main phase"),
        failure: l("Неверные клетки могут дать три занятых сектора в ряд и вайп", "Bad tile choices can complete three claimed spaces in a row and wipe the raid"),
        difficulty: l("На Mythic щит ваятеля снимается двумя диспелами Void Marked", "On Mythic, remove a Voidshaper shield with two Void Marked dispels"),
        spell: spell(1249262),
      },
      {
        id: "blackening-wounds",
        name: l("Чернеющие раны", "Blackening Wounds"),
        tags: ["TANK_SWAP", "DEFENSIVE"],
        who: l("Танки", "Tanks"),
        action: l("Меняйтесь примерно на 8 стаках; перед переходкой активную пачку принимает танк с нужным количеством стаков.", "Swap at roughly 8 stacks; coordinate which tank carries the higher stack count into the intermission."),
        position: l("Босс в выбранной свободной клетке, не в уже занятом секторе", "Boss in the called free tile, never inside an already claimed space"),
        timing: l("Всю основную фазу и перед каждой переходкой", "Throughout the main phase and before every intermission"),
        failure: l("Падает максимальное здоровье танка; неверная позиция также уменьшает получаемый боссом урон", "The tank loses maximum health; bad boss placement also reduces damage taken by the boss"),
        difficulty: l("Базовое правило Normal/Heroic; на Mythic сохраняется", "Baseline Normal/Heroic rule; unchanged on Mythic"),
      },
      {
        id: "pitch-bulwark",
        name: l("Смоляной оплот", "Pitch Bulwark"),
        tags: ["INTERRUPT", "TARGET_PRIORITY"],
        who: l("Назначенная ротация прерываний", "Assigned interrupt rotation"),
        action: l("Кикайте каждый каст Стойкого темного стража или Облитератора; не накладывайте два кика одновременно.", "Interrupt every Stalwart or Obliterator cast and do not overlap two interrupts."),
        position: l("Держите приоритетных аддов собранными не ближе 10 м от босса", "Keep priority adds grouped at least 10 yards from the boss"),
        timing: l("Сразу при появлении полосы каста в переходке", "As soon as the cast bar appears during the intermission"),
        failure: l("Адды получают щиты, переходка затягивается и механики наслаиваются", "Adds gain shields, extending the intermission into overlapping mechanics"),
        difficulty: l("На Heroic дистанция аддов от босса обязательна", "On Heroic, adds must remain separated from the boss"),
      },
      {
        id: "void-fall",
        name: l("Падение Бездны", "Void Fall"),
        tags: ["DODGE", "MOVE"],
        who: l("Все игроки", "All players"),
        action: l("Выйдите из отмеченных луж до срабатывания и оставляйте центр клетки свободным.", "Leave the telegraphed pools before impact and preserve the center of the tile."),
        position: l("Один короткий шаг в чистый сектор, без пересечения лучей порталов", "A short sidestep into clean space without crossing portal beams"),
        timing: l("Во время каждой переходки", "During every intermission"),
        failure: l("Получаете лишний урон и перекрываете путь группе", "You take avoidable damage and block the raid's movement lane"),
        difficulty: l("Повторяется из каждого ранее созданного портала", "Repeats from every portal created earlier in the fight"),
      },
      {
        id: "oblivions-wrath",
        name: l("Гнев забвения", "Oblivion's Wrath"),
        tags: ["DODGE", "MOVE"],
        who: l("Все игроки", "All players"),
        action: l("Смотрите направление копий, уходите между линиями и не возвращайтесь на прежнюю траекторию слишком рано.", "Read the lance directions, move between lanes, and do not step back onto the old path too early."),
        position: l("Между копьями в свободной клетке", "Between lances inside a free tile"),
        timing: l("В переходках после появления копий от босса", "During intermissions when lances fan out from the boss"),
        failure: l("Попадание наносит тяжелый урон; на Mythic копья возвращаются", "A hit deals heavy damage; on Mythic the lances return"),
        difficulty: l("Mythic: запомните исходную линию и уклонитесь от обратного прохода", "Mythic: remember the outgoing line and dodge the return path"),
      },
      {
        id: "shadow-phalanx",
        name: l("Темная фаланга", "Shadow Phalanx"),
        tags: ["DODGE", "MOVE"],
        who: l("Весь рейд", "Whole raid"),
        action: l("Быстро найдите разрыв в движущейся стене неуязвимых солдат и пройдите через него одной группой.", "Find the gap in the moving wall of immune soldiers and pass through it as one group."),
        position: l("Заранее сместитесь к видимому разрыву", "Pre-position toward the visible gap"),
        timing: l("В конце переходок 2, 4 и 6", "At the end of intermissions 2, 4, and 6"),
        failure: l("Стена сбивает позицию и обычно убивает на совпадении с другими зонами", "The wall displaces the raid and commonly kills during overlapping hazards"),
        difficulty: l("Normal/Heroic; на Mythic совпадает с возвращающимися копьями", "Normal/Heroic; on Mythic it overlaps returning lances"),
      },
      {
        id: "gathering-darkness",
        name: l("Сгущение мрака", "Gathering Darkness"),
        tags: ["TARGET_PRIORITY", "DEFENSIVE"],
        who: l("Все бойцы", "All damage dealers"),
        action: l("Мгновенно переключитесь в ваятеля Бездны и убейте его до полного набора энергии.", "Hard-swap to the Voidshaper and kill it before it reaches full energy."),
        position: l("Адд собран у танка, но не рядом с боссом", "Add stacked on the tank but separated from the boss"),
        timing: l("Mythic-переходка, сразу после появления ваятеля", "Mythic intermission, immediately after the Voidshaper appears"),
        failure: l("Адд превращается в опасного Obscurion Endwalker", "The add transforms into a dangerous Obscurion Endwalker"),
        difficulty: l("Только Mythic", "Mythic only"),
        spell: spell(1255749),
      },
    ],
  },
  vorasius: {
    sourceUrl: "https://www.icy-veins.com/wow/vorasius-raid-guide",
    sourceUpdatedAt: "2026-05-19",
    checkedAt: "2026-09-14",
    mechanics: [
      {
        id: "primordial-roar",
        name: l("Первобытный рев", "Primordial Roar"),
        tags: ["STACK", "DEFENSIVE"],
        who: l("Весь рейд и лекари", "Whole raid and healers"),
        action: l("Соберитесь в центре, прожмите запланированный групповой сейв и приготовьтесь к притягиванию с отбрасыванием.", "Stack in the center, use the assigned raid defensive, and prepare for the pull followed by a knockback."),
        position: l("Плотно перед боссом, вдали от боковых стен", "Tightly in front of the boss, away from side walls"),
        timing: l("В начале основной фазы", "At the start of the main phase"),
        failure: l("Разбросанную группу сложнее вылечить, а отбрасывание может отправить в опасную зону", "A spread raid is harder to heal and the knockback can send players into danger"),
        difficulty: l("Одинаковая базовая реакция на Normal/Heroic/Mythic", "Same baseline response on Normal/Heroic/Mythic"),
        spell: spell(1260046),
      },
      {
        id: "shadowclaw-slam",
        name: l("Теневое сокрушение", "Shadowclaw Slam"),
        tags: ["SOAK", "DEFENSIVE", "TANK_SWAP"],
        who: l("Один назначенный танк", "One assigned tank"),
        action: l("Танк принимает круг один. Первый танк держит первые два удара и большой сейв на второй; второй принимает оставшиеся.", "One tank solos the circle. Tank A takes the first two hits with a major defensive on hit two; Tank B takes the rest."),
        position: l("Танковский круг отдельно от рейда, но рядом с центром", "Tank circle separated from the raid but near center"),
        timing: l("Примерно каждые 10–15 секунд", "Roughly every 10–15 seconds"),
        failure: l("Пустой круг наносит смертельный рейдовый урон; лишний игрок получает ненужный дебафф", "An empty circle triggers lethal raid damage; extra players take an unnecessary debuff"),
        difficulty: l("На следующем цикле фазы роли танков меняются", "Tank roles reverse on the next main-phase cycle"),
        spell: spell(1244012),
      },
      {
        id: "aftershock",
        name: l("Повторный толчок", "Aftershock"),
        tags: ["DODGE", "MOVE"],
        who: l("Все, кроме танка во время первоначального удара", "Everyone except the tank during the initial impact"),
        action: l("После Slam зайдите в разрыв между расходящимися кольцами и затем вернитесь в стак.", "After the Slam, move through the gap between expanding rings and then restack."),
        position: l("В безопасном кольце вокруг точки удара", "Inside the safe ring around the impact point"),
        timing: l("Сразу после каждого Shadowclaw Slam", "Immediately after every Shadowclaw Slam"),
        failure: l("Кольцо наносит тяжелый физический урон", "The ring deals heavy Physical damage"),
        difficulty: l("На Mythic механика не меняется, но пространства меньше", "No notable Mythic change, but space is tighter"),
        spell: spell(1273067),
      },
      {
        id: "blisterburst",
        name: l("Огнежальщики / Обжигающий взрыв", "Blistercreeps / Blisterburst"),
        tags: ["MOVE", "TARGET_PRIORITY", "DEFENSIVE"],
        who: l("Игроки с фиксацией, танки и бойцы", "Fixated players, tanks, and damage dealers"),
        action: l("Прижмите аддов вплотную к левой и правой стенам и убивайте только там; отойдите от 8-метрового взрыва.", "Pin adds directly against the left and right walls and kill them only there; clear the 8-yard explosion."),
        position: l("Вплотную к назначенной стене, не ближе к центру", "Flush against the assigned wall, never toward center"),
        timing: l("В переходке до Void Breath", "During the intermission before Void Breath"),
        failure: l("Стена не ломается, лужа портит центр, а взрыв отбрасывает и усиливает входящий урон", "The wall remains, a pool ruins center space, and the explosion knocks back and increases damage taken"),
        difficulty: l("Heroic: нужно 2 взрыва на стену; Mythic: 3, допустима только одна ошибка", "Heroic: 2 explosions per wall; Mythic: 3, allowing only one miss"),
        spell: spell(1259184),
      },
      {
        id: "void-breath",
        name: l("Дыхание Бездны", "Void Breath"),
        tags: ["DODGE", "MOVE"],
        who: l("Весь рейд", "Whole raid"),
        action: l("Смотрите на светящуюся руку босса и бегите к противоположному краю через заранее сломанную стену.", "Read the boss's glowing hand and run to the opposite edge through the wall opened in advance."),
        position: l("Если светится правая рука — влево; если левая — вправо", "Right hand glowing means move left; left hand means move right"),
        timing: l("В конце переходки после убийства огнежальщиков", "At the end of the intermission after killing Blistercreeps"),
        failure: l("Луч смертелен для игроков перед боссом и быстро убивает на своей траектории", "The frontal beam is lethal and rapidly kills anyone caught in its path"),
        difficulty: l("Схема одинакова; на Mythic меньше права на неверно сломанную стену", "Same pattern; Mythic leaves less margin for a wrongly opened wall"),
      },
    ],
  },
  "fallen-king-salhadaar": {
    sourceUrl: "https://www.icy-veins.com/wow/fallen-king-salhadaar-raid-guide",
    sourceUpdatedAt: "2026-05-19",
    checkedAt: "2026-09-14",
    mechanics: [
      {
        id: "void-convergence",
        name: l("Схождение Бездны / Сгустки Бездны", "Void Convergence / Concentrated Void"),
        tags: ["TARGET_PRIORITY", "MOVE"],
        who: l("Все бойцы; танки ведут босса", "All damage dealers; tanks kite the boss"),
        action: l("Сразу убивайте сферы по одной и не позволяйте им коснуться босса. Танк ведет босса так, чтобы сферы оставались в cleave-зоне.", "Kill orbs immediately, one at a time, and never let them touch the boss. The tank kites to keep them in cleave range."),
        position: l("Босс у края с проходом для сфер", "Boss near the edge with a clear orb lane"),
        timing: l("Каждое появление двух сфер", "Every two-orb spawn"),
        failure: l("Касание сферы усиливает босса и приводит к вайпу", "An orb reaching the boss empowers him and causes a wipe"),
        difficulty: l("Heroic: не складывайте два 8-секундных рейдовых DoT; Mythic: старые сферы возвращаются", "Heroic: do not overlap the two 8-second raid DoTs; Mythic: old orbs return"),
      },
      {
        id: "shadow-fracture",
        name: l("Раскол Тьмы / Расколотая проекция", "Shadow Fracture / Fractured Projection"),
        tags: ["INTERRUPT", "STOP", "HARD_CC"],
        who: l("Игроки, назначенные на сектора и ротацию контроля", "Players assigned to sectors and the control rotation"),
        action: l("Каждую проекцию остановите киком или жестким контролем. Игрок с постоянным CC после своей зоны сразу ищет следующую.", "Stop every Projection with an interrupt or hard crowd control. A player using persistent CC immediately checks another sector."),
        position: l("По заранее отмеченным секторам арены", "Across pre-assigned arena sectors"),
        timing: l("Сразу при появлении аддов", "Immediately when adds appear"),
        failure: l("Пропущенный каст оставляет опасную лужу", "A completed cast leaves a dangerous pool"),
        difficulty: l("Mythic: одновременно кикается только одна цель, остальные нужно контролировать", "Mythic: only one target is interruptible at a time; control the others"),
        spell: spell(1254088),
      },
      {
        id: "shattering-twilight",
        name: l("Раскалывающийся сумрак", "Shattering Twilight"),
        tags: ["MOVE", "SPREAD", "DEFENSIVE"],
        who: l("Танк; на Heroic также отмеченные игроки", "Tank; on Heroic, additional marked players"),
        action: l("Вынесите звезду из рейда и направьте линии в пустые сектора. Сначала взрывается танк, затем остальные цели.", "Carry the star away from the raid and aim its lines into empty sectors. The tank detonates first, then other targets."),
        position: l("У края с линиями, направленными мимо стака", "At the edge with lines aimed away from the stack"),
        timing: l("До детонации звездного рисунка", "Before the star pattern detonates"),
        failure: l("Шипы пересекают стак и наносят массовый урон", "Spikes cut through the stack and deal heavy group damage"),
        difficulty: l("Heroic: дополнительные игроки разводят линии отдельно", "Heroic: additional players spread their line patterns separately"),
      },
      {
        id: "despotic-command",
        name: l("Деспотичный приказ", "Despotic Command"),
        tags: ["SPREAD", "MOVE", "DISPEL_MAGIC"],
        who: l("Отмеченные игроки и лекари", "Marked players and healers"),
        action: l("Цели сначала уходят к краю и разрывают дистанцию, затем лекарь диспелит и быстро снимает heal absorb.", "Targets move to the edge and spread first; a healer then dispels and quickly clears the heal absorb."),
        position: l("По разным краям, не рядом с рабочей зоной", "At separate edges, away from the working area"),
        timing: l("Диспел только после выхода цели", "Dispel only after the target is out"),
        failure: l("Пульсирующий круг бьет союзников, а диспел оставляет лужу в неверном месте", "The pulsing circle hits allies and an early dispel drops a pool in the wrong place"),
        difficulty: l("Normal/Heroic/Mythic: порядок «выйти → диспел» сохраняется", "Normal/Heroic/Mythic: keep the move-then-dispel order"),
      },
      {
        id: "destabilizing-strikes",
        name: l("Дестабилизирующие удары", "Destabilizing Strikes"),
        tags: ["TANK_SWAP", "DEFENSIVE"],
        who: l("Танки", "Tanks"),
        action: l("Меняйтесь примерно на 8 стаках или после спадения дебаффа и не ведите босса в сферу.", "Swap at roughly 8 stacks or when the debuff expires, and never kite the boss into an orb."),
        position: l("У края перед окном 100 энергии", "Near the edge before the 100-energy window"),
        timing: l("На автоатаках всю основную фазу", "On melee attacks throughout the main phase"),
        failure: l("Следующие удары становятся смертельными, а неверный маршрут кормит босса сферой", "Following hits become lethal and a bad path feeds an orb to the boss"),
        difficulty: l("Базовая танковская механика всех сложностей", "Baseline tank mechanic on all difficulties"),
      },
      {
        id: "entropic-unraveling",
        name: l("Энтропическое расплетение", "Entropic Unraveling"),
        tags: ["DODGE", "MOVE", "DEFENSIVE", "TARGET_PRIORITY"],
        who: l("Весь рейд", "Whole raid"),
        action: l("Двигайтесь вместе между вращающимися лучами, отдайте групповые сейвы и весь запланированный урон в босса.", "Move together between rotating beams, use raid defensives, and commit planned damage cooldowns into the boss."),
        position: l("Плотной группой в безопасном секторе у края", "As a tight group in a safe edge sector"),
        timing: l("20 секунд на 100 энергии", "For 20 seconds at 100 energy"),
        failure: l("Касание луча каждую секунду наносит тяжелый урон; потеря окна увеличивает длину боя", "Touching a beam deals heavy damage every second; wasting the window extends the fight"),
        difficulty: l("Босс получает +25% входящего урона во время окна", "The boss takes 25% increased damage during the window"),
      },
    ],
  },
  "vaelgor-ezzorak": {
    sourceUrl: "https://www.icy-veins.com/wow/vaelgor-and-ezzorak-raid-guide",
    sourceUpdatedAt: "2026-05-19",
    checkedAt: "2026-09-14",
    mechanics: [
      {
        id: "dread-breath",
        name: l("Жуткое дыхание", "Dread Breath"),
        tags: ["DODGE", "MOVE", "DISPEL_MAGIC"],
        who: l("Выбранная цель, весь рейд и лекарь", "Targeted player, whole raid, and a healer"),
        action: l("Цель направляет широкий конус от рейда; остальные уходят за бок босса. Страх снимается сразу после попадания.", "The target aims the wide cone away; everyone else clears the boss's side. Dispel fear immediately if anyone is hit."),
        position: l("Цель рядом с боссом, но смотрит в пустой сектор", "Target stays near the boss while aiming into an empty sector"),
        timing: l("При повороте Ваэлгора к выбранному игроку", "When Vaelgor turns toward the selected player"),
        failure: l("Конус накрывает рейд и накладывает страх на 9 секунд", "The cone clips the raid and applies a 9-second fear"),
        difficulty: l("Иммунитеты к страху можно назначить заранее", "Fear immunities can be assigned in advance"),
      },
      {
        id: "nullbeam-nullzone",
        name: l("Нуль-луч и Нуль-зона", "Nullbeam and Nullzone"),
        tags: ["SOAK", "MOVE", "DEFENSIVE"],
        who: l("Танк и минимум один помощник; затем весь рейд", "Tank plus at least one helper; then the whole raid"),
        action: l("Помогите танку принять часть луча, чтобы уменьшить зону. После появления связи бегите наружу на 10 м и разорвите ее.", "Help the tank soak part of the beam to shrink the zone. When tethered, run 10 yards outward to snap it."),
        position: l("Луч — перед боссом назначенной группой; разрыв связи — наружу от центра зоны", "Beam in front with the assigned group; snap tethers outward from the zone center"),
        timing: l("Луч 4 секунды, затем немедленный выход из зоны", "Four-second beam followed by an immediate exit from the zone"),
        failure: l("Слишком мало попаданий создают большую зону; медленный выход усиливает притяжение и урон", "Too few beam hits create a large zone; a slow exit increases pull and damage"),
        difficulty: l("Heroic: выход последнего игрока наносит сильный рейдовый взрыв", "Heroic: the last player leaving triggers a heavy raid burst"),
      },
      {
        id: "gloom",
        name: l("Мрак", "Gloom"),
        tags: ["SOAK", "MOVE"],
        who: l("Назначенная группа замачивания", "Assigned soak team"),
        action: l("Заранее встаньте на пути сферы и пропустите ее через нужное число игроков, затем дайте ей уйти к краю.", "Pre-position in the orb path, pass it through the required players, then let it travel to the edge."),
        position: l("Фиксированные левый/правый внешние маркеры", "Fixed left/right outer markers"),
        timing: l("До того, как сфера достигнет края", "Before the orb reaches the edge"),
        failure: l("Недостаточное замачивание создает слишком большую долгую лужу", "Insufficient soaking creates an oversized long-lasting pool"),
        difficulty: l("Heroic: команды чередуются из-за минутного дебаффа; Mythic: нужно 7 игроков и больше позиций", "Heroic: rotate teams due to a one-minute debuff; Mythic: 7 players and additional positions"),
      },
      {
        id: "void-howl",
        name: l("Вой Бездны", "Void Howl"),
        tags: ["SPREAD", "HARD_CC", "TARGET_PRIORITY"],
        who: l("Все игроки и назначенные контролеры", "All players and assigned controllers"),
        action: l("Разойдитесь с персональными кругами, затем соберите появившиеся сферы притягиваниями и остановите их AoE касты.", "Spread personal circles, then group the spawned orbs with grips and stop their AoE casts."),
        position: l("Разложите круги вокруг рейдового стака, аддов соберите в центре", "Drop circles around the raid stack, then group adds in center"),
        timing: l("Сначала spread, сразу после появления — контроль и фокус", "Spread first, then immediate control and focus when adds spawn"),
        failure: l("Адды продолжают кастовать рейдовый урон и растягивают позицию", "Adds continue casting raid damage and pull the formation apart"),
        difficulty: l("Mythic: после первого контроля сферы сами к рейду не подплывают", "Mythic: orbs no longer drift toward the raid after the first stop"),
      },
      {
        id: "twilight-bond-rakfang",
        name: l("Сумеречные узы и Клык Эззорака", "Twilight Bond and Rakfang"),
        tags: ["TANK_SWAP", "DEFENSIVE", "MOVE"],
        who: l("Танки", "Tanks"),
        action: l("Держите драконов не ближе 15 м и меняйтесь боссами после переходки или согласованного Gloom; не стойте за хвостом.", "Keep dragons at least 15 yards apart and swap bosses after the intermission or the agreed Gloom; never stand behind them."),
        position: l("Два противоположных края, морды и хвосты от рейда", "Opposite edges with heads and tails pointed away from the raid"),
        timing: l("Постоянно; смена после переходки", "At all times; swap after the intermission"),
        failure: l("Сближение активирует связь, а накопленный танковский эффект перегружает лечение", "Proximity triggers the bond and the stacking tank effect overwhelms healing"),
        difficulty: l("Правило дистанции действует на всех сложностях", "The separation rule applies on all difficulties"),
        spell: spell(1245645),
      },
      {
        id: "radiant-barrier-shadowmark",
        name: l("Сияющий барьер и Метка Тьмы", "Radiant Barrier and Shadowmark"),
        tags: ["STACK", "SPREAD", "DEFENSIVE", "TARGET_PRIORITY"],
        who: l("Весь рейд; отмеченные игроки выходят", "Whole raid; marked players move out"),
        action: l("В переходке войдите внутрь барьера и убейте Воплощение Полуночи. С меткой уйдите к краю барьера, остальные стоят в центре.", "Enter the barrier and kill the Manifestation of Midnight. Shadowmarked players move to its edge while everyone else stays central."),
        position: l("В центре барьера; метки — по внешней кромке", "Center of the barrier; marks on the outer rim"),
        timing: l("На 100 энергии", "At 100 energy"),
        failure: l("Игрок вне щита погибает от Midnight Flames; метка в центре накрывает группу", "A player outside the shield dies to Midnight Flames; a mark in center hits the group"),
        difficulty: l("Shadowmark появляется на Heroic и выше", "Shadowmark appears on Heroic and above"),
      },
    ],
  },
  "lightblinded-vanguard": {
    sourceUrl: "https://www.icy-veins.com/wow/lightblinded-vanguard-raid-guide",
    sourceUpdatedAt: "2026-05-19",
    checkedAt: "2026-09-14",
    mechanics: [
      {
        id: "avengers-shield",
        name: l("Щит мстителя", "Avenger's Shield"),
        tags: ["SPREAD", "DISPEL_MAGIC"],
        who: l("Отмеченные игроки и лекари", "Marked players and healers"),
        action: l("Разойдитесь кругами, затем лекари снимают дебаффы по команде; не диспельте цели, стоящие вместе.", "Spread the circles, then healers dispel on the call; never dispel targets stacked together."),
        position: l("Отдельные свободные сектора вокруг центра", "Separate open sectors around center"),
        timing: l("При появлении кругов от Беллами", "When Bellamy marks players with circles"),
        failure: l("Круги наносят урон всем рядом и цепная ошибка быстро убивает группу", "Circles damage nearby allies and chained overlaps quickly kill the group"),
        difficulty: l("Mythic: метки получает весь рейд, нужен заранее назначенный массовый диспел", "Mythic: the whole raid is marked, requiring a pre-assigned mass dispel"),
      },
      {
        id: "sacred-shield-blinding-light",
        name: l("Священный щит и Слепящий свет", "Sacred Shield and Blinding Light"),
        tags: ["TARGET_PRIORITY", "INTERRUPT", "DODGE"],
        who: l("Все бойцы и назначенный кик", "All damage dealers and the assigned interrupt"),
        action: l("Дальний игрок приманивает рывок Сенн к краю. Не стойте на линии; сломайте щит и прервите Blinding Light.", "The farthest player baits Senn's charge to the edge. Clear the line, break the shield, and interrupt Blinding Light."),
        position: l("Сенн у края; рейд не на траектории рывка", "Senn at the edge; raid clear of the charge path"),
        timing: l("Сразу после рывка", "Immediately after the charge"),
        failure: l("Рывок задевает игроков, а завершенный каст ослепляет рейд", "The charge clips players and a completed cast blinds the raid"),
        difficulty: l("Работает на Normal/Heroic/Mythic", "Applies on Normal/Heroic/Mythic"),
        spell: spell(1248674),
      },
      {
        id: "divine-shield",
        name: l("Божественный щит", "Divine Shield"),
        tags: ["PURGE", "TARGET_PRIORITY"],
        who: l("Жрец с массовым рассеиванием или назначенные пуржеры", "Priest with Mass Dispel or assigned purgers"),
        action: l("После Bloodlust немедленно снимите щиты со всех боссов; при lust на старте начните Mass Dispel по нулю таймера.", "Immediately remove every boss shield after Bloodlust; for pull lust, begin Mass Dispel at zero on the timer."),
        position: l("Боссы должны попадать в область массового рассеивания", "Bosses must be inside the Mass Dispel area"),
        timing: l("Сразу после каждого Bloodlust/Heroism", "Immediately after Bloodlust/Heroism"),
        failure: l("Рейд теряет основное окно урона", "The raid loses its main damage window"),
        difficulty: l("Одинаковая реакция на всех сложностях", "Same response on all difficulties"),
      },
      {
        id: "boss-auras",
        name: l("Ауры на 100 энергии", "100-energy auras"),
        tags: ["MOVE", "TARGET_PRIORITY"],
        who: l("Танки и весь рейд", "Tanks and whole raid"),
        action: l("Заранее уводите активного босса на край минимум на 40 м от остальных: порядок Беллами → Венел → Сенн.", "Pre-move the active boss to the edge at least 40 yards from the others: Bellamy → Venel → Senn."),
        position: l("Активный босс отдельно, остальные два вместе в центре", "Active boss isolated, the other two together near center"),
        timing: l("Непосредственно перед 100 энергией", "Immediately before 100 energy"),
        failure: l("Aura of Devotion снижает урон по боссам, Aura of Wrath удваивает их урон, Aura of Peace блокирует атаки", "Aura of Devotion reduces boss damage taken, Aura of Wrath doubles their damage, and Aura of Peace blocks attacks"),
        difficulty: l("Heroic: после цикла остается постоянная Consecration", "Heroic: each cycle leaves a permanent Consecration"),
      },
      {
        id: "divine-toll",
        name: l("Божественный благовест", "Divine Toll"),
        tags: ["DODGE", "MOVE"],
        who: l("Весь рейд", "Whole raid"),
        action: l("Смотрите дорожки щитов Беллами и проходите между ними; не пересекайте летящий щит ради урона.", "Read Bellamy's shield lanes and move through the gaps; never cross a moving shield for uptime."),
        position: l("В свободной дорожке на стороне изолированного Беллами", "In an open lane on isolated Bellamy's side"),
        timing: l("Беллами на 100 энергии — циклы 1 и 4", "Bellamy at 100 energy — cycles 1 and 4"),
        failure: l("Щит наносит тяжелый урон и накладывает немоту", "A shield deals heavy damage and silences"),
        difficulty: l("Mythic: может совпадать с усиленными механиками другого босса", "Mythic: may overlap an empowered mechanic from another boss"),
      },
      {
        id: "execution-sentence",
        name: l("Смертный приговор", "Execution Sentence"),
        tags: ["SPREAD", "SOAK", "DODGE"],
        who: l("Четыре отмеченных игрока и их группы замачивания", "Four marked players and their soak groups"),
        action: l("Четыре цели расходятся, каждая принимает свою группу. После удара сразу уклоняйтесь от вращающихся молотов.", "Four targets spread, each with a separate soak group. After impact, immediately dodge the spinning hammers."),
        position: l("Четыре раздельных сектора вокруг Венел", "Four separate sectors around Venel"),
        timing: l("Венел на 100 энергии — циклы 2 и 5", "Venel at 100 energy — cycles 2 and 5"),
        failure: l("Неполное замачивание убивает цель; наложенные круги поражают несколько групп", "An undersoaked circle kills its target; overlapping circles hit multiple groups"),
        difficulty: l("Mythic: Divine Storm дополнительно создает торнадо", "Mythic: Divine Storm also creates tornadoes"),
      },
      {
        id: "tyrs-wrath",
        name: l("Гнев Тира", "Tyr's Wrath"),
        tags: ["SOAK", "DEFENSIVE"],
        who: l("Четыре ближайших назначенных игрока и лекари", "Four assigned nearest players and healers"),
        action: l("Назначенная четверка подходит ближе Сенн и принимает heal absorb; лекари немедленно вылечивают поглощение.", "The assigned four move closest to Senn and take the heal absorb; healers immediately clear it."),
        position: l("Четыре игрока внутри, остальные дальше", "Four players inside, everyone else farther away"),
        timing: l("Сенн на 100 энергии — циклы 3 и 6", "Senn at 100 energy — cycles 3 and 6"),
        failure: l("Случайные игроки получают поглощение, а неверная позиция в Aura of Peace лишает возможности действовать", "Random players receive the absorb and bad Aura of Peace positioning prevents actions"),
        difficulty: l("Mythic: способность накладывается на цикл Беллами через Zealous Spirit", "Mythic: overlaps Bellamy's cycle through Zealous Spirit"),
      },
      {
        id: "judgment-combo",
        name: l("Правосудие → финишер", "Judgment → spender combo"),
        tags: ["TANK_SWAP", "DEFENSIVE"],
        who: l("Танки", "Tanks"),
        action: l("После Judgment сразу меняйтесь угрозой, чтобы усиление не попало под Final Verdict или Shield of the Righteous.", "Swap immediately after Judgment so its amplification does not carry into Final Verdict or Shield of the Righteous."),
        position: l("Держите Венел и Беллами отвернутыми от рейда", "Keep Venel and Bellamy facing away from the raid"),
        timing: l("Каждая связка Judgment и следующего удара", "Every Judgment and follow-up spender combo"),
        failure: l("Следующий танковский удар становится смертельным", "The following tank hit becomes lethal"),
        difficulty: l("Два босса используют связку; все три требуют отдельной угрозы", "Two bosses use the combo; all three maintain separate threat tables"),
        spell: spell(1246736),
      },
    ],
  },
  "crown-of-the-cosmos": {
    sourceUrl: "https://www.icy-veins.com/wow/crown-of-the-cosmos-raid-guide",
    sourceUpdatedAt: "2026-05-19",
    checkedAt: "2026-09-14",
    mechanics: [
      {
        id: "grasp-of-emptiness",
        name: l("Хватка пустоты", "Grasp of Emptiness"),
        tags: ["MOVE", "DODGE", "SPREAD"],
        who: l("Отмеченные игроки", "Marked players"),
        action: l("Отойдите от центра круга, чтобы сузить три стрелы, и направьте их в пустой сектор от рейда.", "Move away from the circle's center to narrow its three arrows and aim them into empty space."),
        position: l("На внешнем краю, стрелы направлены мимо группы", "At the outer edge with arrows aimed away from the group"),
        timing: l("До выстрела из отмеченного круга", "Before the marked circle fires"),
        failure: l("Стрелы пересекают рейд и отнимают безопасное пространство", "Arrows cut through the raid and remove safe movement space"),
        difficulty: l("Heroic: одновременно появляются две цели", "Heroic: two targets appear at once"),
      },
      {
        id: "void-expulsion",
        name: l("Извержение Бездны", "Void Expulsion"),
        tags: ["MOVE", "SPREAD"],
        who: l("Отмеченные игроки", "Marked players"),
        action: l("Вынесите лужу к краю или за направление движения рейда и выйдите до взрыва.", "Drop the pool at the edge or behind the raid's movement direction and leave before detonation."),
        position: l("Не в центре; во второй фазе — позади движущегося стака", "Never in center; in phase two, behind the moving stack"),
        timing: l("До детонации и появления постоянной растущей лужи", "Before detonation and the permanent growing pool appears"),
        failure: l("Лужа перекрывает рабочую область на оставшуюся часть фазы", "The pool blocks working space for the rest of the phase"),
        difficulty: l("Heroic: после первой лужи дополнительные игроки получают последовательные метки", "Heroic: the first pool applies follow-up marks to additional players"),
      },
      {
        id: "void-droplets",
        name: l("Капли Бездны / Оскверняющая сущность", "Void Droplets / Corrupting Essence"),
        tags: ["TARGET_PRIORITY", "MOVE", "DEFENSIVE"],
        who: l("Танк, бойцы и игроки с угрозой аддов", "Tank, damage dealers, and players with add threat"),
        action: l("Сведите капли под текущего полубосса и убейте там, чтобы взрыв дал ему уязвимость; сами не набирайте лишние стаки.", "Bring droplets under the active demiboss and kill them there to apply the damage-taken debuff; avoid taking unnecessary stacks yourself."),
        position: l("Точно под текущей целью Demiar → Vroelus → Morium", "Directly under the active target: Demiar → Vroelus → Morium"),
        timing: l("Каждая волна капель в первой фазе", "Every droplet wave in phase one"),
        failure: l("Без дебаффа теряется окно урона; игроки в круге получают +30% входящего урона за стак", "Missing the debuff wastes damage; players in the circle take 30% increased damage per stack"),
        difficulty: l("Порядок целей и способ использования одинаковы на Normal/Heroic", "Target order and use are the same on Normal/Heroic"),
        spell: spell(1241520),
      },
      {
        id: "null-corona",
        name: l("Нуль-венец", "Null Corona"),
        tags: ["DEFENSIVE", "DISPEL_MAGIC"],
        who: l("Две цели и назначенные лекари", "Two targets and assigned healers"),
        action: l("Лекари приоритетно вылечивают большой heal absorb. Диспел используйте только как аварийный — эффект перепрыгнет на другого игрока.", "Healers directly clear the large heal absorb. Dispel only as an emergency because it jumps to another player."),
        position: l("В радиусе прямого лечения, не уходя с другими метками", "Within direct-heal range unless carrying another mechanic"),
        timing: l("Сразу после наложения", "Immediately after application"),
        failure: l("Невылеченное поглощение оставляет цель без эффективного входящего лечения", "An uncleared absorb prevents effective healing on the target"),
        difficulty: l("Возвращается в фазах 2 и 3", "Returns in phases 2 and 3"),
        spell: spell(1233865),
      },
      {
        id: "silverstrike-arrow",
        name: l("Серебряная стрела", "Silverstrike Arrow"),
        tags: ["MOVE", "TARGET_PRIORITY"],
        who: l("Две отмеченные цели", "Two marked targets"),
        action: l("В первой фазе проведите назначенные стрелы через нужных полубоссов, чтобы снять Umbral Tether; не снимайте уже набранный Corrupting Essence повторно.", "In phase one, route assigned arrows through the correct demibosses to remove Umbral Tether; do not erase existing Corrupting Essence stacks with an unnecessary second hit."),
        position: l("На линии Аллерия → цель → край платформы", "On the line Alleria → target → platform edge"),
        timing: l("Первая пара: Demiar и Vroelus; вторая — Morium и в пустоту", "First pair: Demiar and Vroelus; second pair: Morium and empty space"),
        failure: l("Полубосс остается бессмертным или теряет уязвимость", "A demiboss remains immortal or loses its damage-taken debuff"),
        difficulty: l("Порядок относится к первой фазе Normal/Heroic", "This order applies to phase one on Normal/Heroic"),
        spell: spell(1233602),
      },
      {
        id: "silverstrike-barrage",
        name: l("Серебряный шквал", "Silverstrike Barrage"),
        tags: ["SOAK", "MOVE", "DEFENSIVE"],
        who: l("Весь рейд по назначенной очереди", "Whole raid on an assigned rotation"),
        action: l("Намеренно принимайте выбранные стрелы, чтобы снять замедление, но не две подряд. Все время сопротивляйтесь притяжению к центру.", "Intentionally take assigned arrows to clear slow stacks, but never two in succession. Keep running against the pull toward center."),
        position: l("На траектории назначенной стрелы, затем сразу в безопасную дорожку", "In the assigned arrow path, then immediately back into a safe lane"),
        timing: l("Переходки 1 и 2", "Intermissions 1 and 2"),
        failure: l("Слишком много замедления затягивает в смертельный центр; повторное попадание на Heroic опасно", "Too much slow pulls you into the lethal center; consecutive Heroic hits are dangerous"),
        difficulty: l("Heroic: дебафф запрещает принимать две стрелы подряд", "Heroic: a debuff prevents taking two arrows consecutively"),
      },
      {
        id: "ricochet-barrier",
        name: l("Рикошет Серебряной стрелы и Космический барьер", "Silverstrike Ricochet and Cosmic Barrier"),
        tags: ["INTERRUPT", "STOP", "MOVE", "TARGET_PRIORITY"],
        who: l("Три отмеченных игрока, контролеры аддов и бойцы", "Three marked players, add controllers, and damage dealers"),
        action: l("Соберите и остановите трех аддов на Аллерии, проведите через них цепочку рикошета, затем переключитесь в щит Rift Simulacrum.", "Group and stop the three adds on Alleria, route the ricochet chain through them, then swap to the Rift Simulacrum shield."),
        position: l("Адды светятся белым, если попадают в линию цепочки", "Adds glow white when correctly included in the chain"),
        timing: l("Каждый цикл второй фазы", "Every phase-two cycle"),
        failure: l("Выжившие адды продолжают касты, а непробитый щит ломает цикл смены танков", "Surviving adds continue casting and an unbroken shield disrupts the tank-swap cycle"),
        difficulty: l("После рикошета и пробитого щита танки меняют цели провокацией с места", "After ricochet and shield break, tanks swap targets by taunting from position"),
      },
      {
        id: "voidstalker-sting",
        name: l("Жало охотника Бездны", "Voidstalker Sting"),
        tags: ["MOVE", "DEFENSIVE"],
        who: l("Игроки с накопившимся дебаффом", "Players with stacking debuffs"),
        action: l("Во второй фазе встаньте на путь Silverstrike Ricochet, чтобы стрела сняла стаки. В третьей переживайте их защитой до естественного спадения.", "In phase two, stand in the Silverstrike Ricochet path to clear stacks. In phase three, use defensives until they expire naturally."),
        position: l("Фаза 2 — в подтвержденной линии рикошета; фаза 3 — в общем стаке", "Phase 2 in a confirmed ricochet line; phase 3 in the raid stack"),
        timing: l("До опасного количества стаков", "Before stacks become dangerous"),
        failure: l("Накопленный периодический урон становится смертельным", "Stacking periodic damage becomes lethal"),
        difficulty: l("В третьей фазе снять стрелой уже нельзя", "Cannot be removed by an arrow in phase three"),
      },
      {
        id: "aspect-of-the-end",
        name: l("Облик конца", "Aspect of the End"),
        tags: ["STACK", "MOVE", "DEFENSIVE"],
        who: l("Мили, активный танк, дальний игрок и весь рейд", "Melee, active tank, ranged target, and whole raid"),
        action: l("Разрывайте связи строго мили → танк → после Grasp дальний. После второго набора заберите перо и прыгните на следующую платформу.", "Break tethers strictly melee → tank → ranged after Grasp. After the second set, take a feather and jump to the next platform."),
        position: l("Плотный стак в заднем углу; движение вправо относительно центра", "Tight stack in the back corner, moving right while facing center"),
        timing: l("Каждый набор связей в третьей фазе", "Every tether set in phase three"),
        failure: l("Неверный порядок накладывает опасные механики; поздний прыжок оставляет на разрушенной платформе", "Wrong order overlaps dangerous mechanics; a late jump leaves players on the destroyed platform"),
        difficulty: l("Проверенная тактика Normal/Heroic; Mythic-раздел источника еще не опубликован", "Source-backed Normal/Heroic strategy; the source's Mythic section is not yet published"),
      },
    ],
  },
};

export function getVoidspireMechanicGuide(bossSlug: string) {
  return voidspireMechanicGuides[bossSlug];
}

export function getVoidspireMechanicCount(bossSlug: string) {
  return getVoidspireMechanicGuide(bossSlug)?.mechanics.length ?? 0;
}
