export type BlueprintGame = "platform" | "wow" | "genshin" | "diablo" | "league";

export type Blueprint = {
  slug: string;
  title: string;
  section: string;
  description: string;
  game: BlueprintGame;
  asset: string;
};

export const blueprintGames: Array<{
  id: BlueprintGame;
  label: string;
  mark: string;
}> = [
  { id: "platform", label: "Gildra Platform", mark: "G" },
  { id: "wow", label: "World of Warcraft", mark: "W" },
  { id: "genshin", label: "Genshin Impact", mark: "✦" },
  { id: "diablo", label: "Diablo IV", mark: "D" },
  { id: "league", label: "League of Legends", mark: "L" },
];

export const blueprints: Blueprint[] = [
  {
    slug: "platform/home",
    title: "Cross-game Home",
    section: "Platform",
    description: "Personal meta, saved builds, tracked characters and patch pulse across every game.",
    game: "platform",
    asset: "/ui-blueprints/platform/home/cross-game-dashboard.png",
  },
  {
    slug: "platform/global-search",
    title: "Global Search",
    section: "Platform",
    description: "Unified discovery for characters, classes, items, builds, guides and patches.",
    game: "platform",
    asset: "/ui-blueprints/platform/global-search/fury-results.png",
  },
  {
    slug: "platform/user-profile",
    title: "User Profile",
    section: "Platform",
    description: "A private archive of tracked characters, accounts, favorites and recent activity.",
    game: "platform",
    asset: "/ui-blueprints/platform/user-profile/arcanist-vexis.png",
  },
  {
    slug: "platform/patch-center",
    title: "Patch Center",
    section: "Platform",
    description: "Balance changes, before-and-after values and the resulting movement of the meta.",
    game: "platform",
    asset: "/ui-blueprints/platform/patch-center/league-26-17.png",
  },
  {
    slug: "platform/comparison-lab",
    title: "Comparison Lab",
    section: "Platform",
    description: "Aligned comparisons for builds, heroes, items and specializations.",
    game: "platform",
    asset: "/ui-blueprints/platform/comparison-lab/fury-warrior-mythic-plus.png",
  },
  {
    slug: "wow/arcane-mage",
    title: "Arcane Mage Intelligence",
    section: "Specializations",
    description: "Performance, strengths, builds, stats and dungeon recommendations.",
    game: "wow",
    asset: "/ui-blueprints/games/wow/specialization-intelligence/arcane-mage.png",
  },
  {
    slug: "wow/frost-death-knight",
    title: "Frost Death Knight Intelligence",
    section: "Specializations",
    description: "A second specialization blueprint with a distinct class identity.",
    game: "wow",
    asset: "/ui-blueprints/games/wow/specialization-intelligence/frost-death-knight.png",
  },
  {
    slug: "wow/raid-encounter",
    title: "Raid Encounter",
    section: "Raid",
    description: "Dimensius timeline, positioning, fatal mechanics and raid composition.",
    game: "wow",
    asset: "/ui-blueprints/games/wow/raid-encounter/dimensius-the-all-devouring.png",
  },
  {
    slug: "wow/frost-talents",
    title: "Frost DK Talent Calculator",
    section: "Talents",
    description: "Class, hero and specialization trees with loadout controls.",
    game: "wow",
    asset: "/ui-blueprints/games/wow/talent-calculator/frost-death-knight.png",
  },
  {
    slug: "wow/fury-talents",
    title: "Fury Warrior Talent Calculator",
    section: "Talents",
    description: "Complete Fury trees, authentic icon language and PvP talent selection.",
    game: "wow",
    asset: "/ui-blueprints/games/wow/talent-calculator/fury-warrior.png",
  },
  {
    slug: "wow/mythic-plus-planner",
    title: "Mythic+ Dungeon Planner",
    section: "Mythic+",
    description: "Route, packs, enemy forces, timer, Bloodlust and dangerous abilities.",
    game: "wow",
    asset: "/ui-blueprints/games/wow/mythic-plus-planner/the-rookery-stormbound-standard.png",
  },
  {
    slug: "wow/gear-optimizer",
    title: "Gear Optimizer",
    section: "Characters",
    description: "Current equipment, upgrades, BiS path and item replacement simulation.",
    game: "wow",
    asset: "/ui-blueprints/games/wow/gear-optimizer/fury-warrior.png",
  },
  {
    slug: "wow/rotation-lab",
    title: "Rotation Lab",
    section: "Combat",
    description: "Ability priority, cooldown timeline, Rage flow and lost opportunities.",
    game: "wow",
    asset: "/ui-blueprints/games/wow/rotation-lab/fury-warrior.png",
  },
  {
    slug: "wow/character-audit",
    title: "Character Audit",
    section: "Characters",
    description: "Actionable fixes for talents, equipment, enchants, gems and stats.",
    game: "wow",
    asset: "/ui-blueprints/games/wow/character-audit/arcanist-vexis-fury-warrior.png",
  },
  {
    slug: "wow/combat-log-analyzer",
    title: "Combat Log Analyzer",
    section: "Combat",
    description: "A forensic view of procs, downtime, casts and cooldown alignment.",
    game: "wow",
    asset: "/ui-blueprints/games/wow/combat-log-analyzer/dimensius-fury-warrior.png",
  },
  {
    slug: "wow/raid-roster-planner",
    title: "Raid Roster Planner",
    section: "Raid",
    description: "Composition, buffs, defensive assignments, soak teams and attendance.",
    game: "wow",
    asset: "/ui-blueprints/games/wow/raid-roster-planner/dimensius-mythic.png",
  },
  {
    slug: "wow/pvp-build",
    title: "Fury Warrior PvP Build",
    section: "PvP",
    description: "Regular and PvP talents, arena compositions, matchups and burst sequence.",
    game: "wow",
    asset: "/ui-blueprints/games/wow/pvp-build/fury-warrior-3v3.png",
  },
  {
    slug: "wow/class-hub",
    title: "Warrior Class Hub",
    section: "Classes",
    description: "Arms, Fury and Protection compared across role, difficulty and content.",
    game: "wow",
    asset: "/ui-blueprints/games/wow/class-hub/warrior.png",
  },
  {
    slug: "genshin/raiden-shogun",
    title: "Raiden Shogun Intelligence",
    section: "Characters",
    description: "Abyss performance, signature build, teams, stats and guides.",
    game: "genshin",
    asset: "/ui-blueprints/games/genshin/character-intelligence/raiden-shogun.png",
  },
  {
    slug: "genshin/abyss-planner",
    title: "Spiral Abyss Planner",
    section: "Abyss",
    description: "Two-team chamber planning, elemental checks and clear forecast.",
    game: "genshin",
    asset: "/ui-blueprints/games/genshin/abyss-planner/floor-12.png",
  },
  {
    slug: "genshin/artifact-optimizer",
    title: "Artifact Optimizer",
    section: "Builds",
    description: "Five-slot optimization with main stats, substats and expected damage.",
    game: "genshin",
    asset: "/ui-blueprints/games/genshin/artifact-optimizer/raiden-shogun.png",
  },
  {
    slug: "genshin/team-builder",
    title: "Team Builder",
    section: "Teams",
    description: "Rotation, reactions, Energy flow, resonance and role coverage.",
    game: "genshin",
    asset: "/ui-blueprints/games/genshin/team-builder/raiden-hypercarry.png",
  },
  {
    slug: "genshin/damage-calculator",
    title: "Damage Calculator",
    section: "Combat",
    description: "Auditable ability formula, buffs, resistance, critical and average damage.",
    game: "genshin",
    asset: "/ui-blueprints/games/genshin/damage-calculator/raiden-musou-shinsetsu.png",
  },
  {
    slug: "genshin/weapon-comparison",
    title: "Weapon Comparison",
    section: "Weapons",
    description: "Refinements, team scenarios, performance curves and value verdict.",
    game: "genshin",
    asset: "/ui-blueprints/games/genshin/weapon-comparison/raiden-shogun.png",
  },
  {
    slug: "genshin/farming-planner",
    title: "Farming Planner",
    section: "Progression",
    description: "Resin, materials, domain schedule and time-to-completion forecast.",
    game: "genshin",
    asset: "/ui-blueprints/games/genshin/farming-planner/raiden-shogun-ascension.png",
  },
  {
    slug: "genshin/banner-planner",
    title: "Banner Planner",
    section: "Wishes",
    description: "Pity, guarantee, savings, probabilities and responsible outcome planning.",
    game: "genshin",
    asset: "/ui-blueprints/games/genshin/banner-planner/raiden-shogun-c2.png",
  },
  {
    slug: "genshin/account-audit",
    title: "Account Audit",
    section: "Account",
    description: "Investment priorities, artifact triage, team coverage and a 30-day roadmap.",
    game: "genshin",
    asset: "/ui-blueprints/games/genshin/account-audit/vexis.png",
  },
  {
    slug: "diablo/spiritborn-build",
    title: "Quill Volley Spiritborn",
    section: "Builds",
    description: "Skills, gear, affixes, paragon direction and endgame activity scores.",
    game: "diablo",
    asset: "/ui-blueprints/games/diablo/build-intelligence/quill-volley-spiritborn.png",
  },
  {
    slug: "diablo/loot-intelligence",
    title: "Harlequin Crest Loot Intelligence",
    section: "Items",
    description: "Drop intelligence, affixes, build fit and farming context.",
    game: "diablo",
    asset: "/ui-blueprints/games/diablo/loot-intelligence/harlequin-crest.png",
  },
  {
    slug: "league/ahri-mid",
    title: "Ahri Mid Intelligence",
    section: "Champions",
    description: "Rank performance, core build, runes, matchups and power spikes.",
    game: "league",
    asset: "/ui-blueprints/games/league/champion-intelligence/ahri-mid.png",
  },
  {
    slug: "league/draft-lab",
    title: "Live Draft Lab",
    section: "Draft",
    description: "Pick and ban state, draft leverage, suggestions and win conditions.",
    game: "league",
    asset: "/ui-blueprints/games/league/draft-lab/live-draft.png",
  },
  {
    slug: "league/matchup-page",
    title: "Ahri vs Zed Matchup",
    section: "Matchups",
    description: "Lane plan, power spikes, kill windows and adaptive itemization.",
    game: "league",
    asset: "/ui-blueprints/games/league/matchup-page/ahri-vs-zed.png",
  },
  {
    slug: "league/live-game-companion",
    title: "Live Game Companion",
    section: "Live",
    description: "Ten-player intelligence, threats, objective timings and next actions.",
    game: "league",
    asset: "/ui-blueprints/games/league/live-game-companion/ahri-ranked.png",
  },
  {
    slug: "league/build-rune-builder",
    title: "Build & Rune Builder",
    section: "Builds",
    description: "Runes and item branches adapted to allies, enemies and game state.",
    game: "league",
    asset: "/ui-blueprints/games/league/build-rune-builder/ahri-anti-dive.png",
  },
  {
    slug: "league/team-composition-lab",
    title: "Team Composition Lab",
    section: "Draft",
    description: "Engage, peel, scaling, damage profile, synergy and a phased win plan.",
    game: "league",
    asset: "/ui-blueprints/games/league/team-composition-lab/front-to-back.png",
  },
  {
    slug: "league/player-profile",
    title: "Player Profile",
    section: "Players",
    description: "Match history, champion pool, rank movement and recurring mistakes.",
    game: "league",
    asset: "/ui-blueprints/games/league/player-profile/arcanist-vexis.png",
  },
  {
    slug: "league/match-review",
    title: "Match Review",
    section: "Review",
    description: "Economy, objectives, deaths, tempo and measurable decision forks.",
    game: "league",
    asset: "/ui-blueprints/games/league/match-review/ahri-ranked-victory.png",
  },
  {
    slug: "league/patch-meta-shift",
    title: "Patch Meta Shift",
    section: "Meta",
    description: "Champion movement before and after balance changes with confidence.",
    game: "league",
    asset: "/ui-blueprints/games/league/patch-meta-shift/patch-26-17-mid.png",
  },
  {
    slug: "league/item-comparison",
    title: "Item Comparison",
    section: "Items",
    description: "Cost, build path, damage, opportunity cost and break-even timing.",
    game: "league",
    asset: "/ui-blueprints/games/league/item-comparison/ahri-mage-items.png",
  },
];

export function getBlueprint(slug: string) {
  return blueprints.find((blueprint) => blueprint.slug === slug);
}

export function getBlueprintsForGame(game: BlueprintGame) {
  return blueprints.filter((blueprint) => blueprint.game === game);
}
